### ISSUE TITLE
Improve ergonomics: Add object to group should return boolean rather than throw exception

### ISSUE THREAD

**Issue by 1Dragoon** [microsoftgraph/msgraph-sdk-java#1003]
I'm not sure what the most "Java" way of doing this is, but it seems odd to me that invoking a call like this:

```java
String groupId = "9a6cd538-d064-4b67-b37c-99484a759e98";
DirectoryObject de = new DirectoryObject();
de.id = "d8a65015-2c66-4ea9-8d4c-b2ef331dc7b3";
graphClient.groups(groupId).members().references().buildRequest().post(de);
```

...will throw an exception if the object is already a member of the group. Couldn't this instead return a boolean true/false, i.e. true if the object was added to the group, false if it was already a member and so it wasn't added?

**Comment by baywet** [comment]
Hi @1Dragoon,
Thanks for reaching out.

## General context

This behaviour is driven by the service itself which returns a [400 status code in that case rather, 204 no content in case it's successful](https://docs.microsoft.com/en-us/graph/api/group-post-members?view=graph-rest-1.0&tabs=http#response).
This in turns in driven by [OData conventions](https://www.odata.org/documentation/) the service is following.
This SDK is not handcrafted, it is generated (based on the service metadata and OData conventions), which is why the decision was made to follow protocol standards (returning nothing rather than a boolean value, throwing exceptions on failed responses) to avoid conflicting with other generation cases (OData methods) and to give the SDK user more control.

## This specific case

A boolean return value would not be enough as the response falls within 3 cases during "normal execution":
- 204: added successfully
- 400: already here
- 404: the entity that's being added couldn't be located

(and on top of that you must account for all other non-normal errors like the 500 class and some other 400 error codes)

This is why it is preferable to throw an exception with details, rather than just returning a boolean, this way in your code you can implement a try catch, look at the exception code and the inner exception code (they are constants), and implement recovery behaviour that's specific to the case the application ran into.

[Additional information about Graph errors](https://docs.microsoft.com/en-us/graph/errors)

Hopefully this helps understanding the context, let us know if you have follow up questions/remarks.
