### ISSUE TITLE
AdditionalDataManager API returns NULL

### ISSUE THREAD

**Issue by ponrajit** [microsoftgraph/msgraph-sdk-java#1071]
[segmentJson.txt](https://github.com/microsoftgraph/msgraph-sdk-java/files/8668572/segmentJson.txt)

### Expected behavior

In Call Record objects, the Additional Data Manager for the “caller” or “callee” (within Segment) should contain relevant information.

### Actual behavior

In Call Record object, the segments’ caller/callee Additional Data Managers appear to be empty. This prevents us from extracting information about the caller/callee’s identity.

The code snippet is as follows

```java
CallRecord callRecord = graphServiceClient.communications().callRecords(callId).buildRequest().expand("sessions($expand=segments)").get();
// first session from CallRecord
Session session = callRecord.sessions.getCurrentPage().get(0);
// first segment from Session
Segment segment = session.segments.getCurrentPage().get(0);
// callerIdentityJson from Segment
JsonElement callerIdentityJson = segment.caller.additionalDataManager().get("identity");
```

With older versions of Microsoft graph (2.9.0) and Microsoft graph core (1.0.9), we were able to get the ‘identity’ JSON.
With new versions of Microsoft graph (5.22.0) and Microsoft graph core (2.0.12), this is NULL (additionalDataManager() seems empty).

### Steps to reproduce the [behavior]

1. Attached the Segment JSON.
2. Deserialize the Segment JSON 
Segment segment = (Segment) graphServiceClient.getSerializer().deserializeObject(segmentJson, Segment.class);
3. segment.caller.additionalDataManager().get("identity") will return NULL.

**Comment by baywet** [comment]
Hi @ponrajit ,
Thanks for the very detailed issue description.
The identity information is not in the additional data manager anymore because it is parsed to the identity property of the participant endpoint object.

https://github.com/microsoftgraph/msgraph-sdk-java/blob/7f0459bec4e58ed75e2867f1251a3fa76de7ac25/src/main/java/com/microsoft/graph/callrecords/models/ParticipantEndpoint.java#L46

Because the payload contains `"@odata.type": "#microsoft.graph.callRecords.participantEndpoint",` the segment.caller is in fact a participantEndpoint and not just an endpoint and the property gets populated.

You can access the information by casting the object:

```Java
CallRecord callRecord = graphServiceClient.communications().callRecords(callId).buildRequest().expand("sessions($expand=segments)").get();
// first session from CallRecord
Session session = callRecord.sessions.getCurrentPage().get(0);
// first segment from Session
Segment segment = session.segments.getCurrentPage().get(0);

if (segment.caller instanceof ParticipantEndpoint) {
((ParticipantEndpoint)segment.caller).identity...
}
```

Let us know if you have further questions.

**Comment by ponrajit** [comment]
Thanks for your suggestion. I can access the required information by casting the object.

**Comment by baywet** [comment]
Thanks for confirming, closing. Let us know if you need anything else.
