### ISSUE TITLE
Unable to retrieve Response headers from Graph API response

### ISSUE THREAD

**Issue by rick-scio** [microsoftgraph/msgraph-sdk-java#1247]
Hello! We noticed a new set of RateLimit-* headers available from responses in the [documentation](https://learn.microsoft.com/en-us/sharepoint/dev/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online#ratelimit-headers---preview), which we've also seen in our local testing.

We also noticed that there are some examples to avoid throttling based on these RateLimit-* headers in C#, e.g. https://github.com/OneDrive/samples/tree/master/scenarios/throttling-ratelimit-handling. 

However, looking at the Java SDK, we saw that the `Response` object is processed in a private function: https://github.com/microsoftgraph/msgraph-sdk-java-core/blob/6b69ab84772173e28615895fc906b21f001c877c/src/main/java/com/microsoft/graph/http/CoreHttpProvider.java#L415, and there's no easy handler we can provide that can both process the Response headers and then default to the normal deserialization behavior. The current logic relies on the passed in handler to [also deserialize and interpret the result](https://github.com/microsoftgraph/msgraph-sdk-java-core/blob/6b69ab84772173e28615895fc906b21f001c877c/src/main/java/com/microsoft/graph/http/CoreHttpProvider.java#L435). This causes the header to be hidden away in-code and no straightforward way from what we can find to process the returned headers yet in Java. 

We would like to avoid throttling as much as possible, so is there a recommended way to add a callback handler, similar to the C# excerpt, for us to provide a way to process the `Response` object to interpret the RateLimit-* headers returned as part of the `Response` object? We noticed that one can specify a RetryHandler as part of the HTTPProvider configuration for error logic, so we'd love to know if we're missing any similar functionality here.

Thanks!

**Comment by baywet** [comment]
Hi,
Thanks for reaching out and for using the Java SDK.

The SDKs don't implement a middleware yet for those headers since the implementation on the service side is limited to a single workload (OneDrive/SharePoint), and since the IETF specification is still a draft.
However [I have already created an issue](https://github.com/microsoftgraph/msgraph-sdk-design/issues/82) to update our SDKs requirements when the IETF spec reaches maturity.

As to how to implement the functionality, a middleware handler is most likely the right solution as you don't want to implement that on a per request basis and the implementation will be similar to the [retry handler](https://github.com/microsoftgraph/msgraph-sdk-java-core/blob/dev/src/main/java/com/microsoft/graph/httpcore/RetryHandler.java)

Let us know if you need any additional information.
