### ISSUE TITLE
Submission of PRs should be from a fork

### ISSUE THREAD

**Issue by davidmoten** [microsoftgraph/msgraph-sdk-java#130]
Since day dot the committing team has been contributing from branches in the microsoftgraph/msgraph-sdk-java repo. I don't recommend this method.

What should be happening is that contributers **fork** the microsoftgraph/msgraph repo to their own copy at myusername/msgraph-sdk-java and submit PRs from there. Part of the PR lifecycle involves rebasing and forced pushes which is a dangerous practice when applied to the main repo but of course is completely safe when applied to the user's own copy of the repo.

Another advantage of taking this approach is that it takes some stress away from having to be very careful with your write privileges on the main repository (don't clone that one!).

**Comment by darrelmiller** [comment]
In all the Git projects I have worked on here at Microsoft we have always created branches in the current repo in order to create PRs.  We have a gated master branch to protect from accidental commits.   I am curious as to what part of the PR lifecycle requires you to rebase and force push.  I have never found the need to do that.

Having local branches makes it easier for me to access and try out PRs that are being worked on.

**Comment by davidmoten** [comment]
Ok, no worries. Thought you might be protecting the master (`dev`) branch, that's good and takes a lot of the risk away and I can imagine it's handy being able to track work happening on a single repo. The rebase, forced push scenario is quite common with a PR because while a PR is being reviewed other commits might be merged and the rebase and forced push is needed before the PR can be merged. Thanks for the info, closing.
