### ISSUE TITLE
Unable to append data to an existing file on One drive and Share point

### ISSUE THREAD

**Issue by mohnish92** [microsoftgraph/msgraph-sdk-java#1302]
Hi Team, 
I was going through the official documents to see if there is an example to append data to an existing file on one drive and Share point. 
Unfortunately, I could not find any. Went through the code as well of class LargeFileUploadTask. Seems like the code only writes from offset 0 and there is no append behaviour to the upload method of this class. Can you please let me know if there is an API/SDK class to achieve the same or will this be taken as a new request ? 
All I want is to append data to a file from specific offset to end of file. I can provide data as an input stream, or bytes or any other requested format.
Looking forward for your help in advance.
Thank you

**Comment by mohnish92** [comment]
any update on this ?

**Comment by baywet** [comment]
Sorry for the late reply, we've been working hard [to release a new major version of the SDK](https://devblogs.microsoft.com/microsoft365dev/microsoft-graph-java-sdk-v6-now-generally-available-helps-you-write-simpler-faster-and-more-accurate-code/)
Since this is an issue with the older version, we'll be closing it for now.
Please go ahead and try with this new version, if you're still facing issues, feel free to open a new issue.
