### ISSUE TITLE
if-none-match header does not work

### ISSUE THREAD

**Issue by ankgupta067** [microsoftgraph/msgraph-sdk-java#1312]
### Expected behavior
throw 304 exception

### Actual behavior

does not throw exception even if etag is same

### Steps to reproduce the behavior
i am using microsoft graph java sdk version 5.32.0 and making a call to get drive item , i am also provding etag so that if item is not modified i get a 304 exception , but i never get an exception eventhough item is not modfied and same etag is returned , any issue is there in the below code which is causing this?

```
 var ho = new HeaderOption("if-none-match","{CE8370C2-65E6-4AF5-8B4A-E02C8A29C081},6");
        var options = new ArrayList<Option>();
        options.add(ho);

InputStream driveItem = _userClient.drives().byId("b!XSQmjmdVB0qX4G0WHdLwiuszVcK2AgdInZpWIonRDSyw0hXMWgo8T6LY2EqFsRND")
                .items("01PK4R276COCB45ZTF6VFIWSXAFSFCTQEB").content().buildRequest(options).get(); 

```

**Comment by ankgupta067** [comment]
Hi ,
on checking further i found that i was not passing correct etag when i changed that i do get an exception now but excption is not very informative its of type com.microsoft.graph.core.ClientException and have details like-
`[Error during http request, Abstract classes can't be instantiated! Register an InstanceCreator or a TypeAdapter for this type. Class name: java.io.InputStream]`
is there a way to identify that 304 was the response.

Also if i remove content() and just get DriveItem there i get DriveItem output with all fields as null so again in that how would i know 304 was thrown ?

**Comment by baywet** [comment]
Hi,
Sorry for the late reply, we've been working hard [to release a new major version of the SDK](https://devblogs.microsoft.com/microsoft365dev/microsoft-graph-java-sdk-v6-now-generally-available-helps-you-write-simpler-faster-and-more-accurate-code/)
Since this is an issue with the older version, we'll be closing it for now.
Please go ahead and try with this new version, if you're still facing issues, feel free to open a new issue.
