### ISSUE TITLE
channel: doesUserHaveAccess not working

### ISSUE THREAD

**Issue by SEOJUNGJIN** [microsoftgraph/msgraph-sdk-java#1321]
Hi, I have a problem with the result value being null for the **"channel: doesUserHaveAccess"** request of a channel in **Microsoft Graph SDK Java v5.44.0**.

https://learn.microsoft.com/en-us/graph/api/channel-doesuserhaveaccess?view=graph-rest-1.0&tabs=java

> The result value is null.

`Boolean _boolean = graphClient.teams(teamId).channels(channelId).doesUserHaveAccess(ChannelDoesUserHaveAccessParameterSet.newBuilder().withUserPrincipalName(principalName).build()).buildRequest().get();`

But,

> Request by **"Graph Explorer"** is OK.

`https://graph.microsoft.com/v1.0/teams/{teamId}/channels/{channelId}/doesUserHaveAccess(userPrincipalName='{principalName}')`

I hope this issue will be fixed in the next release.

Thanks.

**Comment by ramsessanchez** [comment]
Hi @SEOJUNGJIN , unfortunately we have seen an issue like this before. My suggestion is to include the UserId as well, if attainable as well as the PrincipleName of the user. Using both of these parameters should allow you to retrieve the desired response.

**Comment by SEOJUNGJIN** [comment]
Please check again. (Even if you try with PrincipleName and UserId, it doesn't work.)

**If you debug, you can see that the Graph API responds normally, but an error occurs when parsing the response value from the Graph SDK Java to a Boolean value.**

thank you.

**Comment by baywet** [comment]
Hi,
Sorry for the late reply, we've been working hard [to release a new major version of the SDK](https://devblogs.microsoft.com/microsoft365dev/microsoft-graph-java-sdk-v6-now-generally-available-helps-you-write-simpler-faster-and-more-accurate-code/)
Since this is an issue with the older version, we'll be closing it for now.
Please go ahead and try with this new version, if you're still facing issues, feel free to open a new issue.
