### ISSUE TITLE
Not correct url build for hunting query

### ISSUE THREAD

**Issue by gilb77** [microsoftgraph/msgraph-sdk-java#1494]
Hi, 

i using version 'com.microsoft.graph:microsoft-graph:5.62.0',

When i build the following build query like in the documentation 

sdkClient
              .security()
              .runHuntingQuery(SecurityRunHuntingQueryParameterSet
                      .newBuilder()
                      .withQuery(query)
                      .build()
                      .buildRequest()
                      .post()

the url build with wrong hunting query segment,

You can find in the class SecurityRequestBuilder the method runHuntingQuery that add "microsoft.graph.runHuntingQuery" segment instead of "runHuntingQuery"

![image](https://github.com/microsoftgraph/msgraph-sdk-java/assets/21139764/263de0da-d5ff-489f-a44d-132611276c40)

**Comment by baywet** [comment]
Hi @gilb77 
Thanks for reporting this. This endpoint is an OData action. They can either be called using their short name (runHuntingQuery) or using their fully qualified names (microsoft.graph.security.runHuntingQuery, notice the missing security segment).
It seems our current generator is not building the right namespace name in front of the action name.
This is something that'll be fixed by the next generation of the Java SDK we're currently working on.

In the meantime, as a workaround, you can use the [request builder constructor](https://github.com/microsoftgraph/msgraph-sdk-java/blob/1ddc2ca04c7d95fd8e006a4b2fb2a51cce349c6a/src/main/java/com/microsoft/graph/requests/SecurityRunHuntingQueryRequestBuilder.java#L31) and pass it the URL manually instead.

**Comment by gilb77** [comment]
thank you @baywet
