### ISSUE TITLE
How to get delta token after full synchronization

### ISSUE THREAD

**Issue by chandrakant-gupta** [microsoftgraph/msgraph-sdk-java#150]
I am trying to fetch records using .
1. using /groups
final List<Option> options = new LinkedList();
options.add(new QueryOption("$skiptoken", nextPageLink));
graphServiceClient.customRequest("/groups").buildRequest(options).get()

when all full synchronization done . We get nextLink null.
Now i want to get deltaToken only so i can get only changes records after that .I am not able to find anything like this .
2. using /groups/delta
final List<Option> options = new LinkedList();
options.add(new QueryOption("$skiptoken", nextPageLink));
graphServiceClient.customRequest("/groups/delta").buildRequest(options).get()

When i use this one i am able to get deltaToken in last but records are different compare than full synchronization using first method .

how can i get deltaToken after full synchronization.

**Comment by NakulSabharwal** [comment]
Thanks for putting up this issue. We are looking into this issue.

**Comment by NakulSabharwal** [comment]
Hi, I am able to repro your issue of not getting deltaToken after full synchronization. We are looking into that. 
Also, can you tell which members you are getting in part 2 with first call of graphServiceClient.customRequest("/groups/delta").buildRequest(options).get().

**Comment by chandrakant-gupta** [comment]
Thank you @NakulSabharwal

**Comment by chandrakant-gupta** [comment]
@NakulSabharwal how can i get owner of any group which is a primary owner of that group ?

**Comment by NakulSabharwal** [comment]
So, you want to know who is the admin of certain org? Please, correct me if I am not wrong.

**Comment by chandrakant-gupta** [comment]
No . I want to know who is a owner of any group which is type Section.

**Comment by NakulSabharwal** [comment]
You can use administrative units for this purpose but its in beta and also you would require permissions Directory.Read.All, Directory.ReadWrite.All and Directory.AccessAsUser.All for doing such query.
Documentation: https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/resources/administrativeunit .
We are considering your issue of getting delta token as resolved. Please reopen this issue if it is not resolved. Thanks.

**Comment by chandrakant-gupta** [comment]
Your suggestions worked .Thank you .

**Comment by shahid-hussain-com** [comment]
Hi @NakulSabharwal,
I have millions of emails in my outlook inbox so to get deltaLink do I need to full synchronization 
I have read MS doc but I didn't find any solution [](https://docs.microsoft.com/en-us/graph/delta-query-overview)
I think its very complex  to sync with millions of email
I need deltaLink instead of nextLink without full synchronization

**Comment by shahid-hussain-com** [comment]
Hi @NakulSabharwal,
I have millions of emails in my outlook inbox so to get deltaLink do I need to full synchronization 
I have read MS doc but I didn't find any solution [](https://docs.microsoft.com/en-us/graph/delta-query-overview)
I think its very complex  to sync with millions of email
I need deltaLink instead of next link without full synchronization
