### ISSUE TITLE
'UnableToDeserializePostBody' error after sending a post request to update a contact

### ISSUE THREAD

**Issue by Fradven** [microsoftgraph/msgraph-sdk-java#1534]
### Expected behavior

I'm trying to update a new contact with a schema extension by calling the Microsoft Graph API.

### Actual behavior

The stack trace i get:

```
Jul 12, 2023 1:53:03 PM com.microsoft.graph.logger.DefaultLogger logError
	SEVERE: CoreHttpProvider[sendRequestInternal] - 408Graph service exception
	Jul 12, 2023 1:53:03 PM com.microsoft.graph.logger.DefaultLogger logError
	SEVERE: Throwable detail: com.microsoft.graph.http.GraphServiceException: Error code: UnableToDeserializePostBody
	Error message: were unable to deserialize

	POST https://graph.microsoft.com/v1.0/users/{user}/contacts/{contacts}/extensions/extdtlnlmgg_contactMetaData
	SdkVersion : graph-java/v5.49.0
		[...]

		400 : Bad Request
[...]

		[Some information was truncated for brevity, enable debug logging for more details]
	Jul 12, 2023 1:53:03 PM com.microsoft.graph.logger.DefaultLogger logError
	SEVERE: CoreHttpProvider[sendRequestInternal] - 408Graph service exception
	Jul 12, 2023 1:53:03 PM com.microsoft.graph.logger.DefaultLogger logError
	SEVERE: Throwable detail: com.microsoft.graph.http.GraphServiceException: Error code: UnableToDeserializePostBody
	Error message: were unable to deserialize

	POST https://graph.microsoft.com/v1.0/users/{user}/contacts/{contacts}/extensions/extdtlnlmgg_contactMetaData
	SdkVersion : graph-java/v5.49.0
		[...]

		400 : Bad Request
[...]

		[Some information was truncated for brevity, enable debug logging for more details]
		13:53:03,442  ERROR [cerebro.manager.MsGraphHelper] Mails TES error
	com.microsoft.graph.http.GraphServiceException: Error code: UnableToDeserializePostBody
	Error message: were unable to deserialize

	POST https://graph.microsoft.com/v1.0/users/{user}/contacts/{contacts}/extensions/extdtlnlmgg_contactMetaData
	SdkVersion : graph-java/v5.49.0
		[...]

		400 : Bad Request
[...]

		[Some information was truncated for brevity, enable debug logging for more details]
	at com.microsoft.graph.http.GraphServiceException.createFromResponse(GraphServiceException.java:419)
	at com.microsoft.graph.http.GraphServiceException.createFromResponse(GraphServiceException.java:378)
	at com.microsoft.graph.http.CoreHttpProvider.handleErrorResponse(CoreHttpProvider.java:512)
	at com.microsoft.graph.http.CoreHttpProvider.processResponse(CoreHttpProvider.java:442)
	at com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:408)
	at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:225)
	at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:202)
	at com.microsoft.graph.http.BaseRequest.send(BaseRequest.java:335)
```

### Steps to reproduce the behavior

My code to checks for a shema extension:

```
SchemaExtensionCollectionPage response = graphClient.schemaExtensions().buildRequest().get();
List<SchemaExtension> extensions = fetchAll(response);
contactExtension = extensions.stream()
    .filter(e-> (contactExtensionId).equals(e.id)) //contactExtensionId fetched from internal DB
    .findAny().orElse(null);

if(contactExtension == null)
{
	contactExtension = new SchemaExtension();
	contactExtension.id = contactExtensionId;
	contactExtension.description = "Contact extension";
	LinkedList<String> targetTypesList = new LinkedList<>();
	targetTypesList.add("contact");
	contactExtension.targetTypes = targetTypesList;
	
	LinkedList<ExtensionSchemaProperty> propertiesList = new LinkedList<>();
	ExtensionSchemaProperty tenantProperty = new ExtensionSchemaProperty();
	tenantProperty.name = EXTENSION_PROPERTY_TENANT;
	tenantProperty.type = "String";
	propertiesList.add(tenantProperty);
	ExtensionSchemaProperty idProperty = new ExtensionSchemaProperty();
	idProperty.name = EXTENSION_PROPERTY_ID;
	idProperty.type = "String";
	propertiesList.add(idProperty);
	contactExtension.properties = propertiesList;
	
	contactExtension = graphClient.schemaExtensions()
			.buildRequest()
			.post(contactExtension);
			
	logger.info("Contact Extension created : " + contactExtension.id);
}
```

Here's the extension for the contact:

```
public static class ContactExtension extends Extension
{
	@SerializedName(value = "tenant", alternate = {"Tenant"})
	@Expose
	@Nullable
	public String tenant;
	
	@SerializedName(value = "entityId", alternate = {"EntityId"})
	@Expose
	@Nullable
	public String entityId;
}
```

And here is how I try to update the contact following the [official documentation](https://learn.microsoft.com/en-us/graph/extensibility-schema-groups?tabs=java) as much as I can :

```
Extension ext = graphClient.users(targetUser.id)
	.contacts(contact.id)
	.extensions(this.contactExtension.id)
	.buildRequest()
	.post(contactExt);
```

**Comment by Fradven** [comment]
I'm sorry for bothering again with this issue but has anyone had the time to look at it?

**Comment by ramsessanchez** [comment]
Hi @Fradven, I have a question regarding the code shared. You describe updating a contact and you also describe creating a schema it seems. Updating would require Patch and Creating a new entity would require Post. Not sure if you are handling the two scenarios differently as I only see code using .post(). Could you clarify if your intention is to Update or Create?

**Comment by Nightbringer42** [comment]
Hi @ramsessanchez, I'm a colleague of @Fradven and I'll try here to clarify what we need, and what is failing.

So we're creating contacts, and for each newly created contact we try to add a schema extension to this contact. This schema extension is pretty simple, it only contains two fields to identify the Exchange contact in our database, as described in the two first code snippets.
We need it in order to differentiate what comes from our application from the other contacts, in order to periodically update their content based on what's encoded in our application.

The last snippet is where we the call fail, we try to post a fresh schema extension instance to link it to the newly created contact, so it's a post because it's the extension that's posted against the contact.

There is a serious lack of documentation for the Java sdk about schema extension, so we did with what we had at disposal.

Can you point us the right way to post a schema extension to a contact ? If you have some fresh doc, that would be nice, but even a working exemple would help us.

Have a nice day,
Gauvain

**Comment by ramsessanchez** [comment]
Hi @Nightbringer42 , 
I believe the issue is with the extension type. The extension posted to the contact should not be a SchemaExtension, but rather just an Extension which is the correct type. When you are passing the schemaExtension id there is an issue because it references a schemaExtension and Contact does not accept that as the correct type. While you are creating the schemaExtension correctly, adding that schemaExtension to the contact is not acceptable. I believe there is a problem with the documentation, I believe the correct documentation link to follow would be: https://learn.microsoft.com/en-us/graph/api/resources/opentypeextension?view=graph-rest-1.0

**Comment by ramsessanchez** [comment]
The following should be a bit more helpful as far as getting you on the correct path to adding this extension with it's properties:
```Java
        Extension extension = new Extension();
        extension.id = "{extension id}";
        AdditionalDataManager manager = extension.additionalDataManager();
        manager.put("tenant", new JsonPrimitive("{tenant}"));
        manager.put("entityId", new JsonPrimitive("{entityId}"));

        graphClient.users("").contacts("").extensions().buildRequest().post(extension);
```
