### ISSUE TITLE
New Feature Request: contentType information for  streaming response types

### ISSUE THREAD

**Issue by mcantrell** [microsoftgraph/msgraph-sdk-java#1602]
There are cases where the API model does not provide contentType information. For instance, there's no way to determine the contentType for:

* ChatMessageHostedContent: [never populated](https://learn.microsoft.com/en-us/graph/api/chatmessagehostedcontent-get?view=graph-rest-1.0&tabs=java#response-1)
* ProfilePhoto: [doesn't exist](ProfilePhoto)

When downloading the content for these models, the contentType is available from the response headers but this is abstracted from the client:

```
InputStream content = client.users(userId)
    .photo()
    .content()
    .buildRequest()
    .get();
```

```
InputStream inputStream = client.users(userId).chats(chatId).messages(messageId).hostedContents(contentId).content()
    .buildRequest()
    .get();
```

It would be beneficial if there was a model for downloadable content that included the useful header response information in addition to the InputStream:

```
class ContentStream {
    public InputStream content; 
    public String contentType;

    // optional fields
    public String contentDispostion;
    public long contentLegth;  
}
```

```
String uri = "/users/%s/chats/%s/messages/%s/hostedContents/%s/$value";
return client.customRequest(uri.formatted(userId, chatId, messageId, contentId), ConContentStreamtentSource.class)
        .buildRequest()
        .get();
```

**Comment by baywet** [comment]
Sorry for the late reply, we've been working hard [to release a new major version of the SDK](https://devblogs.microsoft.com/microsoft365dev/microsoft-graph-java-sdk-v6-now-generally-available-helps-you-write-simpler-faster-and-more-accurate-code/)
Since this is an issue with the older version, we'll be closing it for now.
Please go ahead and try with this new version, if you're still facing issues, feel free to open a new issue.
