### ISSUE TITLE
How to add payment model for metered APIs in Java

### ISSUE THREAD

**Issue by CarlosGuadamuz** [microsoftgraph/msgraph-sdk-java#1603]

**Comment by baywet** [comment]
Sorry for the late reply, we've been working hard [to release a new major version of the SDK](https://devblogs.microsoft.com/microsoft365dev/microsoft-graph-java-sdk-v6-now-generally-available-helps-you-write-simpler-faster-and-more-accurate-code/)
Since this is an issue with the older version, we'll be closing it for now.
Please go ahead and try with this new version, if you're still facing issues, feel free to open a new issue.
