### ISSUE TITLE
Create bulk member user in Azure AD using microsoft graph API by uploading CSV

### ISSUE THREAD

**Issue by Tri16** [microsoftgraph/msgraph-sdk-java#1612]
Hi @darrelmiller, I want to create member users in AD by uploading CSV file, so is there any microsoft graph endpoint using which we can achieve bulk member user creation using CSV?

**Comment by gonisan** [comment]
hi Have you solved this problem? I have the same requirement.

**Comment by baywet** [comment]
Sorry for the late reply, we've been working hard [to release a new major version of the SDK](https://devblogs.microsoft.com/microsoft365dev/microsoft-graph-java-sdk-v6-now-generally-available-helps-you-write-simpler-faster-and-more-accurate-code/)
Since this is an issue with the older version, we'll be closing it for now.
Please go ahead and try with this new version, if you're still facing issues, feel free to open a new issue.
