### ISSUE TITLE
WorkbookWorksheetRangeRequest is missing the patch(WorkbookRange) method, and missing methods in the WorkbookWorksheetRangeRequestBuilder

### ISSUE THREAD

**Issue by dmolaro-jama** [microsoftgraph/msgraph-sdk-java#1756]
The java sdk client is missing the patch method for the methods for WorkbookWorksheetRangeRequest, as well as other methods of the WorkbookWorksheetRangeRequestBuilder class.

com.microsoft.graph
microsoft-graph
5.80.0

Example:
graphClient.me().drive().items("{id}").workbook().worksheets("{sheet-id}")
.range("$A$1").format().font()
.buildRequest()
.patch(workbookRangeFont);

In the WorkbookWorksheetRangeRequestBuilder class, .format() is not available, as well as .clear(), .merge(), .delete() etc...
In the WorkbookWorksheetRangeRequest class, the patch method is missing, so ranges cannot be updated.

I had submitted another ticket for part of this problem a few years back: https://github.com/microsoftgraph/msgraph-sdk-java/issues/289

**Comment by baywet** [comment]
Sorry for the late reply, we've been working hard [to release a new major version of the SDK](https://devblogs.microsoft.com/microsoft365dev/microsoft-graph-java-sdk-v6-now-generally-available-helps-you-write-simpler-faster-and-more-accurate-code/)
Since this is an issue with the older version, we'll be closing it for now.
Please go ahead and try with this new version, if you're still facing issues, feel free to open a new issue.
