### ISSUE TITLE
com.microsoft.aad.msal4j.MsalServiceException AADSTS90013: Invalid input received from the user

### ISSUE THREAD

**Issue by wizardnored** [microsoftgraph/msgraph-sdk-java#1763]
I'm facing this issue : 

Caused by: com.microsoft.aad.msal4j.MsalServiceException: AADSTS90013: Invalid input received from the user. Trace ID: 70ddc41b-0b31-49ce-91eb-f559b03f5e00 Correlation ID: 7c479987-b8c0-48cd-8c1d-f9dd7345c05c Timestamp: 2024-02-01 15:25:08Z

on this line : 
`graphClient.users(mailAdress).messages().buildRequest().filter("isRead ne true").get();`

For the authentication before, i'm using: 

```
final TokenCredential clientSecretCredential = new ClientSecretCredentialBuilder().clientId(proprietesOauth2.get("client_id"))
        .clientSecret(proprietesOauth2.get("client_secret")).tenantId(proprietesOauth2.get("tenant_id")).build();

  final TokenCredentialAuthProvider tokenCredAuthProvider = new TokenCredentialAuthProvider(clientSecretCredential);
    graphClient = GraphServiceClient.builder().authenticationProvider(tokenCredAuthProvider).buildClient();
```

I use these dependencies : 
                <dependency>
		    <groupId>com.microsoft.graph</groupId>
		    <artifactId>microsoft-graph</artifactId>
		    <version>5.80.0</version>
		</dependency>
and 
               <dependency>
		    <groupId>com.azure</groupId>
		    <artifactId>azure-identity</artifactId>
		    <version>1.11.1</version>
		</dependency>

With postman is ok, i can get the token and get messages properly

Thanks for your answer

**Comment by baywet** [comment]
Sorry for the late reply, we've been working hard [to release a new major version of the SDK](https://devblogs.microsoft.com/microsoft365dev/microsoft-graph-java-sdk-v6-now-generally-available-helps-you-write-simpler-faster-and-more-accurate-code/)
Since this is an issue with the older version, we'll be closing it for now.
Please go ahead and try with this new version, if you're still facing issues, feel free to open a new issue.
