### ISSUE TITLE
Unable to get drive item's content: DriveItem.getContet() == null 

### ISSUE THREAD

**Issue by denysobukh** [microsoftgraph/msgraph-sdk-java#1849]
### Expected behavior

DriveItem.getContet() returns not null byte[]

### Actual behavior

DriveItem.getContet() returns `null`

### Code 

```
// results null 
client
  .drives()
  .byDriveId(driveId)
  .items()
  .byDriveItemId(itemId)
  .get().getContent() 


// results 16795  valid value 
client
  .drives()
  .byDriveId(driveId)
  .items()
  .byDriveItemId(itemId)
  .get().getSize()
```

### Libs versions
```
        <microsoft-graph.version>6.2.1</microsoft-graph.version>
        <azure-identity.version>1.11.2</azure-identity.version>
```

### Scopes

![image (1)](https://github.com/microsoftgraph/msgraph-sdk-java/assets/29316853/44902fa4-734c-4dcf-8026-74b009f5444e)

**Comment by ramsessanchez** [comment]
Hi @denysobukh , it seems that, according to documentation, there is a separate endpoint that must be called in order to get the contents. The driveItem resource is not guaranteed to return the contents of the file, likely an optimization from the Api maintainers so as to not return large responses for every call. In order to get the content, you must make a call to `GET /drives/{drive-id}/items/{item-id}/content`
With the SDK this would look like: 
``` java
InputStream item = graphClient.drives().byDriveId(<ID>).items().byDriveItemId(<ID>).content().get();
byte[] bytes = item.readAllBytes();
```

**Comment by denysobukh** [comment]
`getContent()` under `DriveItem` mislead me, it works now    
@ramsessanchez many thanks to you
