### ISSUE TITLE
DefaultAllowedHostsValidator does not exist

### ISSUE THREAD

**Issue by slowcar** [microsoftgraph/msgraph-sdk-java#1850]
The upgrade guide https://github.com/microsoftgraph/msgraph-sdk-java/blob/dev/docs/upgrade-to-v6.md#authentication suggests to use DefaultAllowedHostsValidator, but this class cannot be found in the SDK.

As a workaround i used the set from AzureIdentityAccessTokenProvider

**Comment by baywet** [comment]
I think it's a good idea to maximize reusability.
However, rather than introducing a derived type, I'd just provide a static method that returns an array/set (whatever matches the API in the language) with the default values.
In the case of Java, it'd only be a matter of moving [this](https://github.com/microsoftgraph/msgraph-sdk-java-core/blob/53af3a62d64cf03200a6c9f903929aa2575d44a3/src/main/java/com/microsoft/graph/core/authentication/AzureIdentityAccessTokenProvider.java#L26) to a dedicated public static method.
Do you want to start coordinating things by creating issues in the core repos for all languages?

**Comment by mkomko** [comment]
I just ran into the same problem, please don't forget about this issue. Thanks in advance!

**Comment by baywet** [comment]
@mkomko thanks for the nudge here. Authored #2092
