### ISSUE TITLE
Missing request types in the upgraded version

### ISSUE THREAD

**Issue by varunrathi1910** [microsoftgraph/msgraph-sdk-java#1856]
After upgrading to version 6, certain request types appear to be missing. These include:

"https://graph.microsoft.com/v1.0/sites/{site-id}/sites/{subsite-id}/lists/{list-id}/items/{item-id}" - Retrieving an item from a subsite.
"https://graph.microsoft.com/v1.0/sites/{site-id}/sites/{subsite-id}/lists/{list-id}/drive" - Retrieving details of a drive.
"https://graph.microsoft.com/v1.0/users/{user_id}/messages/{id}/attachments/{id}/$value)" - Fetching attachment content.
"https://graph.microsoft.com/v1.0/appCatalogs/teamsApps" - Publishing a Teams Application via the POST method.

Previously, we used the following requests for these actions:
graphServiceClient.sites("site-id").sites("web-id").lists("list-id").items("item-id").get();
graphServiceClient.sites("site-id").sites("web-id").lists("list-id").drive().get();
FileAttachmentRequestBuilder attachmentRequestBuilder = new FileAttachmentRequestBuilder("https://graph.microsoft.com/v1.0/users/{user_id}/messages/{id}/attachments/{id}", graphServiceClient, null); return attachmentRequestBuilder.content().buildRequest().get();

Along with the upgrade guide, we have referred to the following links for guidance:

https://learn.microsoft.com/en-us/graph/api/attachment-get?view=graph-rest-1.0&tabs=http#http-request
https://learn.microsoft.com/en-us/graph/api/teamsapp-publish?view=graph-rest-1.0&tabs=http#http-request

Are there any alternatives available to execute these requests in upgraded version, or do we need to execute them manually?

Furthermore, would it be advisable for us to transition to v6 in our production environment, or should we wait for further stabilization of the version?

**Comment by baywet** [comment]
Hi @varunrathi1910 
Thanks for using the Java SDK.

List/drive operations on subsites:
To avoid the SDK becoming too large (it supports many more operations the previous one did) we limited the generation to the canonical paths. Because a subsite is still a site, we're not repeating the drives/lists segments under it.
You can either:
- pass the complete id of the subsite instead of the site it, and use that API path instead
- use the withUrl method on the request builder to build the correct target url yourself but still use the fluent API.

app catelogs post is present : https://github.com/microsoftgraph/msgraph-sdk-java/blob/2719abbac71c5a7bd38889b66e7c557612b0ae30/src/main/java/com/microsoft/graph/generated/appcatalogs/teamsapps/TeamsAppsRequestBuilder.java#L94

Message attachment: this is a limitation of how the service documents its metadata unfortunately that doesn't allow us to generate the right code path.
You can use any of the content request builders for the time being and build the URI yourself as a workaround https://github.com/microsoftgraph/msgraph-sdk-java/blob/dev/src/main/java/com/microsoft/graph/generated/teams/item/photo/value/ContentRequestBuilder.java

This version is stable besides the few edge cases due to the change of generation technology and is ready for production. We encourage customers to migrate to it.

Let us know if you have further questions.

**Comment by varunrathi1910** [comment]
Hi @baywet ,
Thank you for suggesting the above alternatives. I also wanted to know if there  is a way to utilize the PageIterator class to iterate over a result set of Strings . When attempting to use the iterator, an error is displayed indicating that String does not extend Parsable and therefore the iterator cannot be utilized. We are currently iterating it manually.

I am attempting to iterate over the following endpoint:
mGraphServiceClient.users().byUserId("user-id").checkMemberObjects()

The compilation error received is:

Bound mismatch: The type String is not a valid substitute for the bounded parameter <TEntity extends Parsable> of the type PageIterator.Builder<TEntity,TCollectionPage>.

**Comment by baywet** [comment]
Currently it's not possible. However with the work ongoing [here](https://github.com/microsoft/kiota-java/pull/1070) it might be in the future.
