### ISSUE TITLE
Jar size almost 50 MB

### ISSUE THREAD

**Issue by andreas-heatly** [microsoftgraph/msgraph-sdk-java#1857]
### Expected behavior
The size of the microsoft-graph jar (https://mvnrepository.com/artifact/com.microsoft.graph/microsoft-graph/6.3.0) file in the 6.x release should not be more than 4 times the size of the 5.x release (https://mvnrepository.com/artifact/com.microsoft.graph/microsoft-graph/5.80.0)

### Actual behavior
The jar size is huge (46.9 MB). Even the old one was huge (11.1 MB), but this breaks size limits for us in some scenarios.

Is there a possibility to divide this into multiple jars somehow? It is, after all, mostly a client library to simplify the usage of a REST API, but we need the models package for it to be useful. As it is now we will have to create our own implementation, which is a bit sad given that there exists a newly revamped client library.

**Comment by baywet** [comment]
Hi @andreas-heatly 
Thanks for using the Java SDK and for reaching out.
Can you expand on the kind of apps you're developing (server, mobile, etc...), why your scenario is sensitive to size and what limits/tolerable sizes are in that scenario please?

This growth in size can be explained by the fact the SDK supports many more endpoints:
- all the excel endpoints were missing due to size limitations
- all the raw counts endpoints ($count) were missing due to the same concern
- etc...

We can't divide up the SDK into multiple packages because it'd lead to arbitrary divisions which would never perfectly match customers' scenarios. Leading to additional complexity and/or duplication.

The definitive size can be reduce a number of ways depending on the scenario:
- through binary trimming like proguard
- through using your own generated client

This new generation of SDK uses [kiota](https://aka.ms/kiota) to project the entirety of the API surface, but in the vast majority of cases applications only need a tiny subset of the ~20 000 operations available on the API.
Kiota supports generating tailored clients that will provide the same exact development experience as this SDK, but for a subset of the API thanks to its filtering capabilities. If your application is size sensitive, we encourage you to try it out!

**Comment by andreas-heatly** [comment]
Hi @baywet,

and thanks for your swift reply. We are running this particular application as a serverless function and in our current deployment process there is a limit of 50 MB for direct upload. There are ways to work around that, but it still feels excessive for the limited amount of functionality we actually use in your library. Given that many services today are microservices, library size issues may often multiply, so I still think it could be worth looking into if there is any kind of modularization that would make (more) sense.

I understand that this will not be a priority, and I will definitely take a look at what Kiota can offer, and if that doesn't work out it is not overly complicated to use the rest endpoints directly. Thanks again for your reply, I think it could be helpful for others getting into similar problems to get an explanation (I guess there are a few out there that hasn't gone through the upgrade yet given the fairly big number of breaking changes).

**Comment by baywet** [comment]
We have worked queued on the documentation front to explain the difference between pre-packaged libraries and self-served clients. And how to get your own self-served client.
@jasonjoh here is another evidence this work is needed in case it helps bump it on the list of piorities.
Since there's nothing to do in the SDK itself, I'll go ahead and close the issue.

**Comment by baywet** [comment]
Update [here is the documentation page](https://learn.microsoft.com/en-us/graph/sdks/generate-with-kiota)
