### ISSUE TITLE
Asking for all sites of groups returns unrealated sites

### ISSUE THREAD

**Issue by rpicot-lecko** [microsoftgraph/msgraph-sdk-java#1868]
### Expected behavior. 
A call to `GET https://graph.microsoft.com/v1.0/groups/{group-id}/sites/` should get all sites related to a group, for example those automatically created in msTeams when a private channel is used.

### Actual behavior.
Seems to return all sites instead
![image](https://github.com/microsoftgraph/msgraph-sdk-java/assets/53426619/c5947c6e-6733-4545-abfb-fc7cd2cdd946)

### Steps to reproduce the behavior. 
1. Make a team A on MsTeams, post messages with attachments to force create the associated sharepoint site to the group.
2. Then create a private channel on teams A to force the creation of a separate sharepoint site associate to the group.
3. make a new team B and post messages with attachments to force create the associated sharepoint site to the group.
4. call `GET https://graph.microsoft.com/v1.0/groups/{group-id}/sites/` with group-ip corresponding to the team A on msTeams.
5. The result is like the screenshot on actual behavior and the site associated to team B appears among others.
6. We would have expected two sites, the root site of A, and the site corresponding to the private channel on team A.

**Comment by baywet** [comment]
Hi @rpicot-lecko 
Thanks for using the java SDK and for reaching out.
This repository is dedicated to issues related to the SDK itself. The service team is not watching it.
Since you're reporting an issue with the service behaviour, you can either open a support ticket, or [reach out on the Microsoft Graph Q&A forum](https://learn.microsoft.com/en-us/answers/tags/161/ms-graph) which the service team is watching.
Closing.
