### ISSUE TITLE
How to avoid Application Insights to be spamed since 6.x.x SDK

### ISSUE THREAD

**Issue by dwlabcube** [microsoftgraph/msgraph-sdk-java#2084]
With Graph SDK 6.13.0 my App-Insights get filled very soon. Each Request logs about 10 InProcs.
How can i disable this?

![image](https://github.com/user-attachments/assets/e5da4040-6fe0-4d67-949e-4cf7ff0d33f9)

**Comment by baywet** [comment]
Hi @dwlabcube 
Thanks for using the Microsoft Graph SDK and for reaching out.
I'm going to assume that you're using the Open Telemetry SDK and have set up application insights as an exporter [similarly to this documentation](https://learn.microsoft.com/en-us/azure/communication-services/quickstarts/telemetry-application-insights?pivots=programming-language-java)
Since the exclusion capability does not seem possible out of the box with this exporter, it seems that you'll have to build a custom one.
I could [only find a python example of doing so](https://github.com/Azure/azure-sdk-for-python/issues/31292#issuecomment-1728672805)
All trace instrumentation names [start with](https://github.com/microsoft/kiota-java/blob/6f9a3219a543fe30525931339e33bd8ad27ae2f3/components/authentication/azure/src/main/java/com/microsoft/kiota/authentication/ObservabilityOptions.java#L15) `com.microsoft.kiota`

Let us know if you have additional questions!

**Comment by dwlabcube** [comment]
Actually i am using the Java-Agent not an exporter.
Some things there can be set via Env-Vars, but unluckily the .._AZURE_SDK_ENABLED being set to false did not solve the issue.

![image](https://github.com/user-attachments/assets/b8ffc810-6e18-44ce-9d0a-fef64c2bb80e)

i thought there might be another env-var to be set.

the spans get set up in kiota here:
https://github.com/microsoft/kiota-java/blob/6f9a3219a543fe30525931339e33bd8ad27ae2f3/components/http/okHttp/src/main/java/com/microsoft/kiota/http/OkHttpRequestAdapter.java#L773

maybe i have to move this issue to the kiota-java repo?

**Comment by baywet** [comment]
yes, it'd make more sense to move this issue to that repository since no telemetry instrumentation is present at this layer.

**Comment by dwlabcube** [comment]
i opened a corresponding ticket
https://github.com/microsoft/kiota-java/issues/1446
