### ISSUE TITLE
sdk size too large

### ISSUE THREAD

**Issue by salomon1184** [microsoftgraph/msgraph-sdk-java#2098]
Since version 6.1.0, the size of the SDK has been increasing significantly, and it has now grown to nearly 60 MB. This increase in size has resulted in downstream users experiencing excessively large package sizes. Could the developers please look into optimizing the packaging to reduce the overall size? Thank you very much for your attention to this matter.

**Comment by baywet** [comment]
Hi @salomon1184 ,
Thank you for using the SDK for reaching out . 
This new SDK supports many more operations than the other one did.
If your scenario is sensitive to the size of the binary, you can instead generate your own SDK and select only the few operations you care about.
Because we use the same generator under the hood you will get the same exact experience.
https://learn.microsoft.com/en-us/graph/sdks/generate-with-kiota

**Comment by salomon1184** [comment]
Hi @baywet ,
Thank you for your prompt response. I will try the method you suggested and close this issue. Once again, thank you very much.
