### ISSUE TITLE
Streaming for large fields?

### ISSUE THREAD

**Issue by davidmoten** [microsoftgraph/msgraph-sdk-java#22]
A FileAttachment has a contentBytes field which in a memory constrained environment environment may exceed heap limits. Does the sdk support streaming of potentially large fields?
[AB#6040](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6040)

**Comment by davidmoten** [comment]
@deepak2016 the initial discussion is about downloads (the code examples talk about InputStreams and reads) so this issue is still valid. Above also talks about holding two copies of a full download in memory which is another problem.

**Comment by deepak2016** [comment]
@davidmoten would you be able to provide any code example with FileAttachment, which will highlight the issue and then we can see how we can enhance that experience?

**Comment by davidmoten** [comment]
>@davidmoten would you be able to provide any code example with FileAttachment, which will highlight the issue and then we can see how we can enhance that experience?

I believe I've explained it sufficiently, code examples pointless.

**Comment by darrelmiller** [comment]
The FileAttachment type is defined as "hasStream" in the metadata and therefore you can use the $value path segment to retrieve the data as a stream.  This is documented (here)[https://docs.microsoft.com/en-us/graph/api/attachment-get?view=graph-rest-1.0&tabs=http#get-the-raw-contents-of-a-file-or-item-attachment].

Unfortunately it is not easy get at this requestbuilder due to use exposing attachments using the base class.  You can use the FileAttachmentStreamRequestBuilder if you supply the URL but it isn't very convenient. 

We have been thinking on this and are wondering if we can add some additional request builders that introduce the OData cast segment to ensure we are getting building a request to the correct type of attachment and therefore can expose the `content` property that would allow direct access to the stream.

```
graphClient.users.getById("").messages.getById("sdsd").attachments.getbyId('')  // current way of getting an attachment
graphClient.users.getById("").messages.getById("sdsd").fileAttachments.content().get()  // proposed way of getting derived collections
graphClient.users.getById("").messages.getById("sdsd").itemAttachments.getById("")
```
Please excuse the pseudo Java.

**Comment by baywet** [comment]
thanks for the patience on the matter.

I've authored #509 to implement odata cast. 

The solution for attachments would then have been 

```Java
graphClient.me().messages("id").attachmentsAsFileAttachment("id").content().get()
```

The issue is that attachments do not currently support OData cast. Generating a fluent API to query as FileAttachment without the OData cast (assuming the thing being returned will be a file attachment) would introduce a whole other set of issues.
So while this doesn't fully fix the issue, it's a step in the right direction. And the benefit is that you'll now be able to do things like

```Java
final IUserCollectionWithReferencesPage usersPage = graphServiceClient
		.groups("id")
		.membersAsUser()
		.buildRequest()
		.get();
```
which makes filtering the data that is sent over the wire and casting in the right client side type much simpler.
