### ISSUE TITLE
OneDrive Upload of Very Large files never finishes

### ISSUE THREAD

**Issue by zstout-vs** [microsoftgraph/msgraph-sdk-java#287]
Hello,

I have had marginal success using the MSGraph SDK to upload files to OneDrive but have run into an issue.

I am working through a process that uploads _very_ large files, something like 10GB+ zip files. I have had success uploading files less than or equal to ~2GB files.

When attempting to upload files larger than 2GB (ranging up to 15 GB at the moment) the upload process appears to complete successfully. However when I visit the target location in OneDrive the upload appears as attached below and never finishes processing (going from tmp file to zip file).

<img width="306" alt="Screen Shot 2019-08-22 at 1 37 26 PM" src="https://user-images.githubusercontent.com/54416626/63544268-02caaa00-c4e2-11e9-817c-a44591142136.png">

I am hoping that this is either resolvable or someone can help identify a limitation I am unaware of.

Thanks

**Comment by katestoycheva** [comment]
Hi @zstout-vs,
I had the same issue as you. I guess you are uploading large files using the official example: https://docs.microsoft.com/en-us/graph/sdks/large-file-upload?tabs=java

The solution is to get the file size using `File.length()` method:
`long streamSize = file.length();`
instead of
`long streamSize = (long)fileStream.available();` 
as it is shown in the sample.

This happens because `fileStream.available()` returns the available bytes as integer and integer's max value in bytes is ~2GB.

I hope this helps you.

**Comment by ddyett** [comment]
@jasonjoh possible sample update.

**Comment by jasonjoh** [comment]
Definitely! Thanks for catching this @katestoycheva! I'll update this, but I encourage you if you find more issues like this in the Graph docs to file an issue using the "This page" button in the **Feedback** section of the page. You can even submit a pull request to fix it :).

**Comment by baywet** [comment]
@jasonjoh reviewing the issues here. According to you, is there any action we need to take in the SDK at this point?

**Comment by jasonjoh** [comment]
I don't think so.

**Comment by baywet** [comment]
thanks. closing
