### ISSUE TITLE
OutOfMemoryError when API is retrying requests

### ISSUE THREAD

**Issue by NilayDhamecha** [microsoftgraph/msgraph-sdk-java#288]
Hello!
We recently upgraded to version 1.6.0 and tried using the retry capability of the library.
However when we are facing OutOfMemoryError and the complete process is getting aborted our assumption about why this error is occurring is that since msgraph-sdk-java is using okhttp3 to retry the requests and somehow this retry is spawning a lot of threads because of which we are getting this OutOfMemoryError .
The logs are attached below.
Can someone please confirm if they are facing the same problem?
Also can someone confirm whether this is the problem in the SDK?
OutOfMemoryError.txt
[AB#6050](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6050)

**Comment by baywet** [comment]
Hi @NilayDhamecha 
Thanks for the feedback and for the patience on that.
This is likely because the retry handler wasn't disposing the previous response when retrying.
I've authored PR https://github.com/microsoftgraph/msgraph-sdk-java-core/pull/74 which should fix this issue and which will close this issue when merged.
