### ISSUE TITLE
FlagStatus is always null.

### ISSUE THREAD

**Issue by monicager** [microsoftgraph/msgraph-sdk-java#321]
### Expected behavior
Message.flag.flagStatus should have one of FollowupFlagStatus value: 
    NOT_FLAGGED,
    COMPLETE,
    FLAGGED,

### Actual behavior
Message.flag.flagStatus is always null

### Steps to reproduce the behavior
Flag a message, when do mClient.me().messages(), all messages has flag.flagStatus value in null.

**Comment by MIchaelMainer** [comment]
I'm fairly confident that the reason why you see this set to null is because you didn't explicitly request this property. The service doesn't return this property and its state. The deserializer doesn't have a value to deserialize so by default, the value is null. 

The fix is to explicitly select this property.
