### ISSUE TITLE
Please help me in Graph Communications API on Android Studio

### ISSUE THREAD

**Issue by sdtech-yangjian** [microsoftgraph/msgraph-sdk-java#338]
I am developing an Android app in which audio/video calls can be made among Windows Teams users. I am trying to use the Graph Communications API, the code below is the code I am pasting onto the Android Studio project, I added all the import things, and I added the dependencies in the build.gradle, but I am still getting the errors like below.

It says "cannot resolve the symbol"
[AB#6053](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6053)

**Comment by davidmoten** [comment]
Try `Call call = new Call();` (you hava case wrong)

**Comment by sdtech-yangjian** [comment]
Sorry, the wrong case is a mistake.
But with the case right, I got a error saying the Call has multiple options, there are two of them, Call (android.telecom) and Call (okhttp3). I don't know this very well, but a Call (com.microsoft.graph.communications.calls) or some thing like that is supposed to be there?
Please help me in this. Thank you very much.

**Comment by wimvanhouts** [comment]
My knowledge of eastern language is not really up to speed (actually I don't have any), but, the below code is a working example of creating a call if you provide all the right classes (Disclaimer 1: I'm using Eclipse to develop an application that runs on Windows/Linux/Docker java application... so this is not in Android Studio (though shouldn't make that much of a difference)). Also take into account you must set the tenant ID on the call or you'll get an exception (tenant mismatch exception, as documented in the MS Graph Reference documentation in the comments section, by different people). Also, it helped me to create the list and objects of type base class and instantiate them with the specific class (don't really know what thy was necessary), and, I also set the ODataType explicitly because this is not done by the SDK, and, else it returns issues when call the SDK (Disclaimer 2: could be I'm not using the latest version of the SDK so this might not be necessary anymore). Also notice that modalities is not longer a string value to provide but an enumeration value (as I also remarked in the MS Graph reference documentation comments). 

![image](https://user-images.githubusercontent.com/12234274/75006935-ca496000-5473-11ea-97af-81e0dabc8b8a.png)

**Comment by sdtech-yangjian** [comment]
@wimvanhouts  Thank you so much! Yeah, my android studio is in Japanese. I am trying to reset it in English, Haha. 
I have no idea if I installed the SDK in the right way...   Am I suppose to download the SDK code and integrate the SDK code into my project? or I just need to follow the installation guide here, only add the jcenter() and the dependency into my build.gradle?
Please help me.

**Comment by wimvanhouts** [comment]
I use gradle as in the below image. I'm using MSAL library for identity platform v2. Wrote blog about it here: https://xqting.com/msgraphandmsalinjavaformsteams. As mentioned before, I'm developing on Eclipse for Windows/Linux application, I don't know whether on Android this is completely equivalent.

![image](https://user-images.githubusercontent.com/12234274/75015605-51ed9980-5489-11ea-9b72-44b7e84fabb6.png)

**Comment by sdtech-yangjian** [comment]
@davidmoten  
I added the SDK in my code in Android Studio (the repository and the dependency).
And I have all the imort added as below,

import com.microsoft.graph.authentication.*;
import com.microsoft.graph.concurrency.*;
import com.microsoft.graph.core.*;
import com.microsoft.graph.http.*;
import com.microsoft.graph.logger.*;
import com.microsoft.graph.models.extensions.*;
import com.microsoft.graph.models.generated.*;
import com.microsoft.graph.options.*;
import com.microsoft.graph.requests.extensions.*;
import com.microsoft.graph.serializer.*;

then the Call() is supposed to be able to be called as a function of communications api, am I right?

**Comment by sdtech-yangjian** [comment]
@wimvanhouts  Thank you for replying me. I am still facing some problems. Would you please share the code with me? Really need your help.

**Comment by baywet** [comment]
Hey @sdtech-yangjian 
It seems like your original question about the type reference was answered.
As this issue is fairly old, I'll go ahead an close it.
When you have questions about Microsoft Graph and the Java SDK the best thing to do is to post on https://stackoverflow.com with the microsoft-graph and the java tags. Issues on GitHub are dedicated to discussing issues and improvement with the SDK itself.
