### ISSUE TITLE
resourceProvisioningOptions missing from Group class

### ISSUE THREAD

**Issue by mkomko** [microsoftgraph/msgraph-sdk-java#349]
Groups have a property called "resourceProvisioningOptions" which can be used to determine if the group corresponds to a team. See: https://docs.microsoft.com/en-us/graph/teams-list-all-teams?context=graph%2Fapi%2F1.0&view=graph-rest-1.0#get-a-list-of-groups

But this property is missing from the SDK.

**Comment by davidmoten** [comment]
Looks like it's missing from the 1.0 OData metadata (but present in beta). If supported it should be added to the v1.0 metadata (then this SDK regenerated).

I've noticed problems before with the metadata and have raised issues against the documentation pages in the hope that it would make it to the right team to fix. @MIchaelMainer best place to report this stuff?

**Comment by MIchaelMainer** [comment]
Hello @davidmoten as you noticed, we haven't been active here lately. We are [hiring](https://careers.microsoft.com/us/en/job/791405/Software-Engineer-II) a new dev to help us with the Java story and once onboarded, we'll be moving this library forward again. 

This is the correct place to let us know about bugs and missing features.

**Comment by davidmoten** [comment]
@MIchaelMainer glad to hear you're hiring. I do think this library needs a very experienced dev with a lot more java experience.

In terms of bugs and missing features you're saying that if I raise problems with the OData metadata  itself or Graph json interaction (e.g. missing json metadata) that you'll escalate them to the appropriate team? Painful, because we lose visibility of progress and can't discuss with that team. I'm hoping for a more direct forum.

**Comment by MIchaelMainer** [comment]
@davidmoten  Yeah, it is painful, but we currently don't have another option, that is unless someone has premier support, which there is a way to open bugs against Microsoft Graph service APIs. There is some monitoring of StackOverflow posts by some teams but there isn't universal coverage.

**Comment by davidmoten** [comment]
@MIchaelMainer thanks, yep I've used both those methods, not very effectively. I'm not sure if raising issues on the github repo for Graph documentation is effective but I've tried that too. You are still my silver bullet for raising stuff!

**Comment by MIchaelMainer** [comment]
@davidmoten  I can try. I really appreciate your feedback, criticism, and guidance over the last few years. Trust me, it pains me to leave so much opportunity unaddressed.

**Comment by baywet** [comment]
Hey everyone,
Good news, we now have a [beta sdk](https://github.com/microsoftgraph/msgraph-beta-sdk-java) and the property is there!
Thanks for the feedback and the patience on the matter.
Closing

**Comment by mkomko** [comment]
I apologize in advance for posting in this closed issue. Can you please explain what the availability of this property in the beta SDK means for this SDK?
As I understand, the beta SDK is for the beta endpoint. But the property is in use in the v1 endpoint, just not available in this SDK.

Thanks in advance!

**Comment by baywet** [comment]
Beta is the place where the different service teams experiment with their APIs, iterate, and eventually when an endpoint, a property, or an entity is ready, it graduates and is made available in v1.

Both SDKs coexist, the v1 SDK (this) allows you to call v1 APIs, the beta SDK (the one linked in my previous comment) allows you to call the beta APIs.
Until the property is made available in v1, it will only be available in beta and you'll have to use the beta SDK to access it. Now keep in mind that beta APIs can break at any time and are not suitable for production use.
The main limitation today is you can't use both the v1 and the beta SDKs in the same application because their package name conflicts, and switching a whole application to beta for a single property seems extreme.

[We have plans](https://github.com/microsoftgraph/msgraph-beta-sdk-java/issues/49) to enable applications to use both the v1 and the beta SDK, this way you'd be able to use the beta SDK specifically for the things that are not available in v1 yet, and the v1 SDK for everything else, getting the best of both worlds. I suggest you go subscribe to that issue to be updated about the progress we make on this one.

**Comment by mkomko** [comment]
Thank you for your extensive reply! Here is what I don't understand: The property **resourceProvisioningOptions** can be used using the v1 endpoint. We have been doing so for a while. It's just that we have to use the additionalDataManager to access it instead of its own property. So if the property is available using the v1 endpoint, shouldn't it have its own property in the User object of this SDK as well?

**Comment by baywet** [comment]
right, I didn't get the fact the service was returning the information but it's not documented in the v1.0 metadata, hence why it's not present as a property. I found [an existing issue](https://github.com/microsoftgraph/msgraph-sdk-serviceissues/issues/44) documenting the fact that property is missing. I suggest we continue the discussion there. Also as a precision, this property is only available on the Group type in beta, not the User type as far as I understand.

**Comment by mkomko** [comment]
Thanks for pointing out the other issue, we can continue there! And yes it's about the Group type, sorry for the mixup. I edited my post above.
