### ISSUE TITLE
Getting file from drive doesn't return @microsoft.graph.downloadUrl property

### ISSUE THREAD

**Issue by slavag** [microsoftgraph/msgraph-sdk-java#369]
Hi.
I'm trying to get file information and then content. 

### File info :
So, I'm doing next call :
`String request = String.format("/sites/%s/drives/%s/root:/%s", siteId, driveId, filePath);
JsonObject obj = graphClient.customRequest(request).buildRequest().get();
`
And getting 404 : Not found. But file is there.
So I downloaded Microsoft Graph Postman collection and tried to get file info there, by calling same API and I got the file. So I started to dig and found that in Microsoft Graph Postman collection they are using header : 
`Prefer=apiversion=2.1`
So I removed that header in postman and also there got "Item not found".

When I did :
`List<HeaderOption> headers = new ArrayList<>();
`
`
headers.add(new HeaderOption("Prefer", "apiversion=2.1"));
`
`
String request = String.format("/sites/%s/drives/%s/root:/%s", siteId, driveId, filePath);
`
`
JsonObject obj = graphClient.customRequest(request).buildRequest().get();
`

I got file info. 
But, when I'm changing request to get file content it' works fine without Prefer header:
`String request = String.format("/sites/%s/drives/%s/root:/%s:/content", siteId, driveId, filePath);
`
`
BufferedInputStream is = graphClient.customRequest(request, BufferedInputStream.class)
.buildRequest().get();
`
And I getting stream with file content.

**So first question what is this header and why without it I can't find file ?**

### File content :
I got file info but it doesn't contains @microsoft.graph.downloadUrl field in it:
  {
"@odata.context": "https://graph.microsoft.com/v1.0/$metadata#sites('domain.sharepoint.com%2Ccc767111-*%2Cc0ef7f82-*')/drives('b%22k4l2zKLNsk62Log2MF8UIBtTYFV')/root/$entity", 
  "cTag": "\"c:{0e8182ec-5ee9-41e6-96ba-372340f873cb},1\"", 
  "createdBy": {
    "user": {
      "displayName": "Slava", 
      "email": "slava@domain.onmicrosoft.com", 
      "id": "1bf721e3-d0f7-4238-88a9-7e13f22efa01"
    }
  }, 
  "createdDateTime": "2020-03-22T20:29:23Z", 
  "eTag": "\"{0E8182EC-5EE9-41E6-96BA-372340F873CB},1\"", 
  "file": {
    "hashes": {
      "quickXorHash": "cwjdhie41VYT6k3bdKT/y30bKX0="
    }, 
    "mimeType": "application/pdf"
  }, 
  "fileSystemInfo": {
    "createdDateTime": "2020-03-22T20:29:23Z", 
    "lastModifiedDateTime": "2020-03-22T20:29:23Z"
  }, 
  "id": "01J7TAN47MQKAQ52K64ZAZNORXENAPQ46L", 
  "lastModifiedBy": {
    "user": {
      "displayName": "Slava", 
      "email": "slava@domain.onmicrosoft.com", 
      "id": "1bf721e3-d0f7-4238-88a9-7e13f22efa01"
    }
  }, 
  "lastModifiedDateTime": "2020-03-22T20:29:23Z", 
  "name": "A Survey of Applications of Markov Decision Processes.pdf", 
  "parentReference": {
    "driveId": "b%22k4l2zKLNsk62Log2MF8UIBtTYFV", 
    "driveType": "documentLibrary", 
    "id": "01J7TAN123Y2GOVW7725BZO354PWSELRRZ", 
    "path": "/drives/b%22k4l2zKLNsk62Log2MF8UIBtTYFV/root:"
  }, 
  "size": 6590404, 
  "webUrl": "https://domain.sharepoint.com/sites/Test/Shared%20Documents/A%20Survey%20of%20Applications%20of%20Markov%20Decision%20Processes.pdf"
}

So, to get download URL I need to call to call GET http call to 
`/sites/{site-id}/drive/root:/{item-path}:/content`
Then I'm getting 302 response with Location header with the URL, so now to be able to get content from Sharepoint file and validate that file downloaded is fine (using hash), I need to do 3 calls , first to get all file metadata, then call to get Location URL and then real call to get a content.

**Why @microsoft.graph.downloadUrl is not returned in the call ?**

Thanks

**Comment by darrelmiller** [comment]
Hey @ificator do you have any insight into this issue?  And can you give some clarity on the apiversion prefer header.  Thanks.

**Comment by ificator** [comment]
QQ: If you query `%s/drives/%s/root:/%s` do you see the `@microsoft.graph.downloadUrl`? Since you have the `driveId` you might not need to specify the site, and I'm curious to hear if that makes a difference.

**Comment by slavag** [comment]
@ificator if i query /drives/%s/root:/%s where first %s is drive id and second %is file path.  I'm also not getting `@microsoft.graph.downloadUrl`, actually the response looks exactly the same.
Thanks

**Comment by ificator** [comment]
So there are a couple of things at play:
1. You should not be using `ApiVersion=2.1` as it does not have feature parity with the default version - that's why you're seeing the lack of `@microsoft.graph.downloadUrl`
1. There's no reason the default version shouldn't return the item in question if it does with `ApiVersion=2.1`. My only theory on this is that maybe there's some encoding related differences - could you provide an example value for `%s` (file path). If you'd rather not tell us the unmodified path feel free to replace any of the letters/numbers but leave anything that's %encoded alone (e.g. `my%20file2.jpg` -> `aa%20aaaaa.aaa`)

**Comment by slavag** [comment]
@ificator Hi,
File is : https://domain.sharepoint.com/sites/Test/Shared%20Documents/A%20Survey%20of%20Applications%20of%20Markov%20Decision%20Processes.pdf
So %s that stands for file path is A%20Survey%20of%20Applications%20of%20Markov%20Decision%20Processes.pdf
You can see it in response I put above. Web browser opens it fine. As you can see there's only white space that is escaped.
Thanks

**Comment by ificator** [comment]
Thanks - sorry, I didn't notice it in the request.

That seems fine, so to debug further we'll need the `request-id` and `Date` headers from the response for the case where you're seeing the unexpected 404.

**Comment by slavag** [comment]
Pease
```
{
  "error": {
    "code": "itemNotFound",
    "message": "Item not found",
    "innerError": {
      "request-id": "e89189cd-5081-4ff8-a2d4-1c210038b1d7",
      "date": "2020-05-23T08:55:06"
    }
  }
}
```

**Comment by ificator** [comment]
The failure is actually indicating that the `site` with the id `xxx.sharepoint.com,cc767993-*,c0db7f82-*` is not found. How did you get that id? At a glance it looks like it was probably obtained using a call with `ApiVersion=2.1` because the second GUID in the id (`c0db7f82-*`) is an indication of such. As I alluded to earlier - there are differences between `ApiVersion=2.1` and the default version, and in this case the ID is not accepted by the latter.

In general I would strongly advise that you do NOT include `Prefer: ApiVersion=2.1` in **any** of your requests.  Can you tell me what "Microsoft Graph Postman collection" represents? Is it something you downloaded or did you capture some traces yourself? I'm curious to understand how you discovered this `Prefer` value to see if there's something we should fix to avoid developer confusion like this.

**Comment by slavag** [comment]
@ificator thanks Brad,
The id of the site was find by calling 
`https://graph.microsoft.com/v1.0/sites`
Called it twice now with apiversion=2.1 and without it - got same id, no difference.
Now, I would like not to use apiversion=2.1, actaully learned about it from postman collection for MS Graph API published in MSDN ( I think). 
Anyway when I called now `/sites/%s/drives/%s/root:/%s` with site ID only, not the id returned from  `https://graph.microsoft.com/v1.0/sites`
But only with siteId I got a @microsoft.graph.downloadUrl (didn't use apiversion=2.1).
So, question in that call `/sites/%s/drives/%s/root:/%s` what should be id for the site ? is it siteid or ID ?
Thanks

**Comment by slavag** [comment]
@ificator Brad, I found something more interesting , when I'm calling `https://graph.microsoft.com/v1.0/sites ` response is :
```
{
            "createdDateTime": "2019-01-03T13:29:07Z",
            "id": "domain.sharepoint.com,cc767993-,c0db7f82-",
            "lastModifiedDateTime": "2020-05-25T07:21:58.9265722Z",
            "name": "Test",
            "displayName": "Test",
            "webUrl": "https://cloudally1.sharepoint.com/sites/Test",
            "sharepointIds": {
                "siteId": "cc767993-",
                "siteUrl": "https://domain.sharepoint.com/sites/Test",
                "tenantId": "472fa13e-",
                "webId": "c0db7f82-"
            },
            "siteCollection": {
                "hostname": "domain.sharepoint.com"
            },
            "root": {}
        }
```
Now, when I'm calling : `https://graph.microsoft.com/v1.0/sites/domain.sharepoint.com:/sites/Test/` I'm getting different ID :

**Comment by ificator** [comment]
Thanks for the details - I have an idea what's going on but it's Memorial Day long weekend here and so I won't hear back from the dev that owns this area to confirm.

Stepping back, what are you trying to accomplish by hitting `/sites`? Technically that's an undocumented endpoint, and in the past it would have thrown an error if you tried to hit it. The fact that it's not throwing an error but also not returning valid values for the site's `id` is a bug, and the "fix" will most likely be, at least for the short term, to make it fail again. That obviously means you won't be able to take a dependency on it just yet, and so we'll need to understand your intent to suggest an alternative. However, assuming you're just trying to find all of the sites within a tenant, you could try a search:
```
https://graph.microsoft.com/v1.0/sites?search=*
```

**Comment by slavag** [comment]
@ificator Actually I saw https://docs.microsoft.com/en-us/graph/api/site-list?view=graph-rest-beta&tabs=http, but now I see that it's beta, anyway it should work correctly, as this post is relatively new I assumed that is something that I can use. 
But yes, I tried to enumerate all sites.
Thanks

**Comment by ificator** [comment]
That's actually, somewhat misleadingly, documenting how you can find the root site collections in the tenant (I.e. how you can discover the various geo locations in which a tenant resides). That's why it's documenting the specific filter and select statements that must be required.

I'll update this issue tomorrow once I've had a chat with the team.

**Comment by slavag** [comment]
@ificator Hi Brad, is there any update ? Thanks

**Comment by ificator** [comment]
Sorry, "tomorrow" turned out to be longer than expected ;)

It looks like the fix for the bad ids is actually rolling out now and so we'll keep this new API active for now. You should hopefully see the issue resolved over the course of the week.

I'll still underscore that this is new functionality that is not yet documented (i.e. officially released) and so as a result there may be other issues that you encounter. There'll be an update to our [scan guidance](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/scan-guidance) documentation when it's officially ready.

**Comment by slavag** [comment]
@ificator I see that it was changed and now it's returns strange result , while using `?search=*` returns :
`domain.sharepoint.com,cc767993-*,5560531b-*  ` without `?search=*`  returns :
`domain.sharepoint.com,cc767993-*` 

Also that call doesn't returns sub-sites, so the only way to get sub-sites using search on specific site ?  
And another question :
Call `https://graph.microsoft.com/v1.0/sites/domain.sharepoint.com,cc767993-*/drives` to get list of drives, returns only "Documents" drives, but no any "System" documents drives like "Site Pages" and so, to get all drives we found that call  `https://graph.microsoft.com/v1.0/sites/domain.sharepoint.com,cc767993-*/drives?select=id,weburl,system` returns all, but this is strange as `?select=id,weburl,system` it's just says what fields I want to get. This behaviour where ? parameter changes behaviour if what drives returned is not clear to me. Can you please put some light here ? 
Thanks

**Comment by slavag** [comment]
@ificator maybe you missed my previous comment :)

**Comment by ificator** [comment]
Sorry :)

The site enumeration system doesn't actually have the `webid` for the root web, but the site identifiers support falling back to the root web if only one GUID is provided, so:
```
domain.sharepoint.com,cc767993-*
```
is equivalent to:
```
domain.sharepoint.com,cc767993-*,5560531b-*
```
in the case where `5560531b-*` is the id of the root web.

And yes, it will only return the root webs and so if you need to discover all the sub-webs for a site you'd need to query each in turn.

You found the right approach for discovering the other types of "drives", and I agree that it's not standard. The intent when we came up with those semantics was to allow an "enlightened" application to query for data that isn't returned by default. There were three ways to do that:
1. Use a `filter`
1. `select`
1. Add a `prefer` header value

Using a `filter` kinda made sense, but it still had the problem that it's a little strange because you'd have to have a filter like `filter=system eq null or system ne null` to say you want everything. A preference would have been unambiguous but would have required clients to have full control over the headers they provide, which is not always true for all OData frameworks. So we landed on `select` with intention being that if you ask for `system` that implies you know what it means and we can safely return the values that would have otherwise been hidden.

If we start over would we do it this way again? Probably not, but it's unfortunately part of the contract now.

**Comment by slavag** [comment]
@ificator Thanks Brad. This helped a lot to understand. You mentioned filter, select and prefer. So what about prefer header ? is it not recommended to use it ? What are values for this header ?

Thanks a lot !!!

**Comment by ificator** [comment]
It was an implementation option that was not pursued - unfortunately the only way to see the "system" drives is to use the `select` syntax.
