### ISSUE TITLE
Feature Request: JSR 310 time

### ISSUE THREAD

**Issue by lespea** [microsoftgraph/msgraph-sdk-java#442]
Not sure what everybody else's feelings on the matter are, but dealing with Calendar objects is pretty painful. It would be great if all of the date/time fields were switched to ZonedDateTime or something equivalent in jsr 310.  This would obviously be a pretty breaking change so I can understand if it isn't something you want to do. 
[AB#7610](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7610)

**Comment by baywet** [comment]
Thanks for the feedback!
@darrelmiller any opinion on this one?

**Comment by baywet** [comment]
After meeting with Darrel, we'll consider it for our next major version. Thanks!

**Comment by baywet** [comment]
related #546

**Comment by baywet** [comment]
additional information, switching to this would require raising the API level to 26 and customers/partners targeting a lower API level to desugar. https://developer.android.com/reference/java/time/ZonedDateTime

**Comment by baywet** [comment]
@lespea Thanks for your patience on the matter. After a lot of internal back and forth over which android API level the library should support, it looks like we settled on 21 (see #546). Now, we're currently in a transition period to support that API level properly as I explain [here](https://github.com/microsoftgraph/msgraph-sdk-java-core/pull/42#issuecomment-749005767) as one of our dependencies is not ready yet for android.

None the less, on the long term plan, we want to support API level 21, and switching to this API instead would push us to drop support for API levels 21 to 25 or require consumers to desugar their applications.
Additionally, even if we'll have to ship variants because of our dependencies, we don't want to fork the current code-base in two different code bases for Android and Java.

Thank you again so much for the suggestion, we'll have to decline implementing it for the reasons outlined above. Closing.

**Comment by baywet** [comment]
Update: I'm reopening this as other elements force us to bump to API level 26 which would unlock this as well.
[See the original discussion](https://github.com/microsoftgraph/msgraph-sdk-java-core/pull/42#issuecomment-759559062)

**Comment by baywet** [comment]
Update: I have just submitted the pull request for version 3 here #612
OffsetDateTime seemed to be much more appropriate for service communication, and I ended up choosing it over ZonedDateTime. 
Don't hesitate to leave feedback on the pull request and thanks for the suggestion!
