### ISSUE TITLE
For ColumnDefinition currency there is no maximum and minimum property 

### ISSUE THREAD

**Issue by vishwavagyani** [microsoftgraph/msgraph-sdk-java#486]
There is no maximum and minimum property for com.microsoft.graph.models.extensions.CurrencyColumn

**Comment by baywet** [comment]
Hey @vishwavagyani 
Thanks for the feedback.
This is not available in the java sdk because the property is not available in [Microsoft Graph today](https://docs.microsoft.com/en-us/graph/api/resources/currencycolumn?view=graph-rest-1.0).
To request support for this property, please ask/upvote an idea on [UserVoice](https://microsoftgraph.uservoice.com).
Closing
