### ISSUE TITLE
Dependencies are no longer transitively added to consumer projects

### ISSUE THREAD

**Issue by schuch** [microsoftgraph/msgraph-sdk-java#494]
With the [upgrade to gradle 6](https://github.com/microsoftgraph/msgraph-sdk-java/pull/435) all dependencies were set to scope `implementation`. This means, their are no longer transitively added with compile scope to consumer projects.

### Expected behavior
The POM [microsoft-graph-2.2.0.pom](https://repo1.maven.org/maven2/com/microsoft/graph/microsoft-graph/2.2.0/microsoft-graph-2.2.0.pom) should have compile time dependencies to
- gson
- ~~guava~~ (update: not part of public api)
- microsoft-graph-core
- ~~okhttp~~ (update: is compile time dependency of microsoft-graph-core)

### Actual behavior
The POM [microsoft-graph-2.2.0.pom](https://repo1.maven.org/maven2/com/microsoft/graph/microsoft-graph/2.2.0/microsoft-graph-2.2.0.pom) lists the dependencies from above with scope `runtime`.

### Solution
Scope dependencies that are part of the API with scope `api` in `build.gradle`.

### Background
With gradle 6 the old `compile` scope was deprecated and split into `implementation` and `api`: https://youtu.be/7ll-rkLCtyk?t=29m18s

More explanation can be found here: https://stackoverflow.com/questions/44493378/whats-the-difference-between-implementation-and-compile-in-gradle

### Why is this a problem?
Consumer Projects currently need to manage those dependencies by themselves. This makes upgrades to newer versions harder, because it is easy to introduces bugs by using wrong dependency versions.

**Comment by baywet** [comment]
Hey @schuch 
Thanks for reaching out. The main reason why I decided to go with implementation rather than API is because we've had a few customers having duplicate sub-dependencies errors. For example #457 .
Now I understand there might be a middle ground here where we switch to API only the [dependencies that are exposed in our public api](https://stackoverflow.com/a/44419574/3808675)
This would probably include:
- microsoft-graph-core
- gson
And exclude:
- guava: not exposed publicly
- okhttp: already exposed by core

Thoughts?

**Comment by schuch** [comment]
Sounds good to me. I updated the issue description accordingly.

**Comment by baywet** [comment]
Authored #496 which will close this issue when merged.
