### ISSUE TITLE
Drive root children API failing in Android OS 5

### ISSUE THREAD

**Issue by atulgpt** [microsoftgraph/msgraph-sdk-java#530]
Getting com.microsoft.graph.core.ClientException: Error during http request when calling OneDriveGraphServiceClient.me().drive().root().children()

Full stacktrace: 
com.microsoft.graph.core.ClientException: Error during http request
10-05 10:18:01.628 E/connectors_debug( 8565): 	at com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:429)
10-05 10:18:01.628 E/connectors_debug( 8565): 	at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:204)
10-05 10:18:01.628 E/connectors_debug( 8565): 	at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:184)
10-05 10:18:01.628 E/connectors_debug( 8565): 	at com.microsoft.graph.http.BaseCollectionRequest.send(BaseCollectionRequest.java:89)
10-05 10:18:01.628 E/connectors_debug( 8565): 	at com.microsoft.graph.requests.extensions.DriveItemCollectionRequest.get(DriveItemCollectionRequest.java:64)
10-05 10:18:01.628 E/connectors_debug( 8565): 	at 

10-05 10:18:01.628 E/connectors_debug( 8565): **Caused by: java.lang.IllegalArgumentException: Unknown pattern** **character 'X'**
10-05 10:18:01.628 E/connectors_debug( 8565): 	at java.text.SimpleDateFormat.validatePatternCharacter(SimpleDateFormat.java:314)
10-05 10:18:01.628 E/connectors_debug( 8565): 	at java.text.SimpleDateFormat.validatePattern(SimpleDateFormat.java:303)
10-05 10:18:01.628 E/connectors_debug( 8565): 	at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:356)
10-05 10:18:01.628 E/connectors_debug( 8565): 	at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:249)
10-05 10:18:01.628 E/connectors_debug( 8565): 	at com.microsoft.graph.serializer.CalendarSerializer.deserialize(CalendarSerializer.java:121)
10-05 10:18:01.628 E/connectors_debug( 8565): 	at com.microsoft.graph.serializer.GsonFactory$2.deserialize(GsonFactory.java:95)
10-05 10:18:01.628 E/connectors_debug( 8565): 	at com.microsoft.graph.serializer.GsonFactory$2.deserialize(GsonFactory.java:86)
10-05 10:18:01.628 E/connectors_debug( 8565): 	at 

### Expected behavior
API should not fail

### Actual behavior
API is failing. It seems that while parsing the date there is an exception which is apparent from the line: Caused by java.lang.IllegalArgumentException: Unknown pattern** **character 'X'

### Steps to reproduce the behavior
Query the OneDriveGraphServiceClient.me().drive().root().children() api with Android OS version 5

**Comment by baywet** [comment]
Hey @atulgpt 
Thanks for reaching out.
That's because the java API version available on such devices doesn't support parsing the date format returned by Microsoft Graph.
You can add support for it using desugaring, see my comment on a similar issue https://github.com/microsoftgraph/msgraph-sdk-java/issues/286#issuecomment-692148327

**Comment by atulgpt** [comment]
Hi @baywet is there any other way/hack to fix the issue. Adding desugaring lib add size to the app as well as will have major testing impact? I am assuming that you are referring to coreLibraryDesugaring option in build.gradle

**Comment by baywet** [comment]
Not that I know off. The alternative would be for us to test the java API version and fallback on a supported pattern. But that would introduce another issue with time zones and dates being inaccurate.

**Comment by atulgpt** [comment]
Hi @baywet only usage of 'X' is not supported in pre-android version and I tried finding its usage but couldn't understand much. Not sure if this will lead to time zone errors or wrong time being shown. Its a big limitation for every client using this recommended SDK. The old SDK(Android SDK) was deprecated and in newer one we are getting issues with latest Java api usage and we also have to add coreLibraryDesugaring which also increases size and testing impact.

**Comment by baywet** [comment]
I understand the pain being shared, I'm not sure we can do anything about it though.
There is where the X pattern is being used https://github.com/microsoftgraph/msgraph-sdk-java/blob/dev/src/main/java/com/microsoft/graph/serializer/CalendarSerializer.java#L103

FYI for version 3.0 we're planning to upgrade the library's java API version to 1.8 as this was not done but dependencies on java 8 are effectively in place causing issues like you're experiencing.
We're also planning to switch to JSR 310 as outlined by #442. All of that will require desugaring on your side if you want to have support for runtimes <1.8.

**Comment by atulgpt** [comment]
Hi @baywet I have tried running core lib desugaring at my local clone of the project and I am able to use JSR310 apis like Instant or LocalDateTime but SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSXXX") still throws the exception of Unknown pattern character 'X' and your API is still failing due to this
Core desugaring lib version: com.android.tools:desugar_jdk_libs:1.0.10

**Comment by atulgpt** [comment]
Hi @baywet can we not parse 'Z' in iso8601 standard by replacing it with +0000 and parsing against the pattern 'Z' instead of pattern 'X'? I am not if this will lead to wrong parsing in some edge cases.We could do it under Java version check

**Comment by atulgpt** [comment]
@baywet Are you able to look into above comments?

**Comment by baywet** [comment]
@atulgpt thanks for the additional information.
Replacing +0000 by Z is not an option as the service can respond with other offsets depending on headers passed in by the client, service (mailbox/site) settings and other factor. It'd introduce inconsistent behavior (even if we did it only in combination with version check).
Again, we're looking at replacing the use of Calendar by the JSR 310 API as outlined in #442 this is why we **won't be spending time patching this serializer as it'll go away**.
Desugaring the new Time class should be easier as far as I understand: https://code.luasoftware.com/tutorials/android/android-use-java-time-with-java8-liberary-desugaring/
Lastly, if you're concerned about application size because of desugaring, please go support the proguard rules fix which should drastically reduce the size of the application https://github.com/AzureAD/microsoft-authentication-library-for-android/pull/1161 Customers and partners voices always have a bigger impact.
We're also making changes to reduce this library's size with version 3. So far we've dropped about 2MB, hopefully we can reduce it more.
Closing

**Comment by baywet** [comment]
@atulgpt Thanks for your patience on the matter.
At this point we're tentatively targeting API level 21 and work is still in progress.
Can I ask you to try core with the `feature/api-level-baseline` branch, and this service library with `feature/api-level-baseline` branch in your project to double check it solves this issue please?
