### ISSUE TITLE
It will be helpful if we add attribute or property (like bodyWithoutSignature) for email body without signature inside  com.microsoft.graph.models.extensions.Message model.

### ISSUE THREAD

**Issue by vnukasani** [microsoftgraph/msgraph-sdk-java#596]
Hi Team,

Few people might need some kind of requirements like : to read only email content without signature from the email body. 

Now a days in a real time applications we are using Graph API to read emails and send emails etc. 
It will be helpful if we add attribute or property (like bodyWithoutSignature) for email body without signature inside  com.microsoft.graph.models.extensions.Message model.

IMessageDeltaCollectionPage delta = graphClient.users("UUID").mailFolders("Inbox").messages()
	.delta()
	.buildRequest()
	.get();
	
In the above case if we get Message model, and add property like bodyWithoutSignature...
we are easily get message.getBodyWithoutSignature();

**Comment by baywet** [comment]
Hi @vnukasani,
Thanks for the suggestion. This is something the service would have to implement first before it's available in the SDK.
That's because there's no clear demarcation in the body between the signature and the actual content itself, so it'd be hard to implement something simple and consistent in the SDK.
Can I suggest you cross post your idea over to https://microsoftgraph.uservoice.com if it doesn't already exist (in which case you can simply upvote it). If the idea gets enough traction from the community, the product team will consider adding it to the service.

I'm going to go ahead and close this issue and we keep the issues here for things about the SDK itself.
