### ISSUE TITLE
Using graph sdk to interact with outlook rest api

### ISSUE THREAD

**Issue by slowcar** [microsoftgraph/msgraph-sdk-java#702]
Hi,

we have an android app that utilizes EWS. We would like to add some features that are only available with the REST API.

I have implemented this SDK, and it works correctly with the graph endpoint. But we would need a second user interaction to authorize, as (and please correct me if i am wrong!) the authorization endpoints cannot issue a token for different audiences.
Our EWS token has "aud": "https://outlook.office365.com" while a graph token has the graph audience.
The MSAL library is not able to handle different audiences at once, so using EWS and Graph together looks impossible without manual implementation.

Because of that, i would like to use the outlook rest api. I can use setServiceRoot on the GraphServiceClient to set the endpoint (https://outlook.office.com/api/v2.0).
But creating a calendar event fails with a UnableToDeserializePostBody error, and after comparing the samples from the documentation pages i discovered why:
The outlook api requires attributes to start with a capital letter, e.g. "Body", while the graph api uses lowercase, e.g. "body". 
Capitalizing all attributes in my graph sdk request lets me execute it in Postman against the outlook api. (WTF, who thought that this was a good idea???)

Looking at the generated json i see SerializedName using an alternate value, so it seems somebody is aware of this difference and built this to allow the graph sdk to deserialize responses from the outlook endpoint.

Sorry about the long winding introducetion, but:
Is there an option to use the graph sdk with the outlook rest api?

 
[AB#8633](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8633)

**Comment by slowcar** [comment]
sometimes writing all this stuff into a ticket seems to help.
I managed to resolve this by myself.
While i cannot add different audiences in one oauth2 request, i get the correct graph token from msal if i use a fully qualified name for the scopes.
e.g.
`private static final String[] SCOPES = {"https://outlook.office365.com/EWS.AccessAsUser.All"};`
`private static final String[] GRAPH_SCOPES = {"https://graph.microsoft.com/Calendars.ReadWrite", "https://graph.microsoft.com/User.Read"};`

**Comment by baywet** [comment]
Hi @slowcar ,
Thanks for reaching out and I'm glad you figured out a solution.
Warning, be mindful of the language you use here, we want to keep these discussion a safe place for everyone. (use of WTF)

To clarify a few things here:
- The authentication libraries (Azure Identity, MSAL) are meant to be used against any Microsoft resource/service that accepts JWT bearer tokens. Making sure you specify the scopes with the resource prefix like you mentioned will allow you to request tokens for different services. You'll have to request one token per service/resource you want to access, don't mix scopes meant for different resources in a single access token request.
- The Microsoft Graph Java SDK is built and meant to be used against Microsoft Graph, while using it against Outlook REST V2 might work, this is not something that's "officially supported". The default authentication provider [won't attach tokens to requests that are not going to Graph as a security precaution](https://github.com/microsoftgraph/msgraph-sdk-java-core/blob/4056e92dd90dac9fc469eccefb2237a4f87c6a32/src/main/java/com/microsoft/graph/authentication/BaseAuthenticationProvider.java#L14) for example.
- Outlook REST v2 and Microsoft Graph email & calendar APIs are really close but they differ due to historical reasons. Microsoft's recommendation is to use Microsoft Graph as it already contains most of the Outlook REST APIs, and Graph will give you access to 1000's more APIs from a single token/endpoint (drive, chats, intune, identity,...).
