### ISSUE TITLE
Setting connection timeout with v3.0.0

### ISSUE THREAD

**Issue by AllenConquest** [microsoftgraph/msgraph-sdk-java#704]
I am trying to migrate from 2.9.0 to 3.0.0. I have hit a problem with building the new GraphServiceClient. Currently I provide it with a IHttpProvider, so I can control the connection timeout. I use this code:

    final IHttpProvider myHttpProvider = DefaultClientConfig
        .createWithAuthenticationProvider(myAuthProvider)
        .getHttpProvider(myHttpClient);

    myHttpProvider
        .getConnectionConfig()
        .setConnectTimeout(CONNECTION_TIMEOUT);

However the `DefaultClientConfig` doesn't seem to exist in the new version. How would I achieve the same results in the new library?

Thanks,

Allen 
[AB#8656](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8656)

**Comment by baywet** [comment]
Hi @AllenConquest 
Thanks for reaching out and for upgrading to the latest version.
This is something that can be done directly by customizing the http client now through the [connectTimeoutMillis property](https://square.github.io/okhttp/4.x/okhttp/okhttp3/-ok-http-client/connect-timeout-millis/). 
The documentation changes for v3 haven't been published yet, so here is the [staging documentation on how to customize the client with v3](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/sdks/customize-client.md#java)

**Comment by AllenConquest** [comment]
Hi @baywet 
That is fantastic! I'm loving the new simplicity of 3.0.0. Is there now a way to do retries in Java?

**Comment by baywet** [comment]
Glad to hear that @AllenConquest !
Retry for what kind of events? OkHttp already retries for network events (connection drops etc...)  and [the retry handler](https://github.com/microsoftgraph/msgraph-sdk-java-core/blob/dev/src/main/java/com/microsoft/graph/httpcore/RetryHandler.java) automatically retries on 429, 503, 504 for rewindable requests.

**Comment by AllenConquest** [comment]
I am now using the LargeFileUploadTask to upload files to SharePoint. I occasionally see failed attempts, and wondered if there is a way to get it to retry on failure.

**Comment by baywet** [comment]
because the task relies on the standard http pipeline for the SDK, it should already retry automatically on network failures and transient http statuses. We've had feedback in the past that the retry mechanism doesn't necessarily log a lot of information which makes it hard to understand whether the request was retried or not before returning an error.

Maybe this is some feedback you could [explicitly call out in the core library](https://github.com/microsoftgraph/msgraph-sdk-java-core/issues/new) so we queue the work.

If you're experiencing errors with the large file upload frequently, please let us know with a lot of details so we can look into that.
I'm going to go ahead and close this issue because we're digressing from the original topic :)
