### ISSUE TITLE
IAuthenticationProvider and Android support

### ISSUE THREAD

**Issue by dabarnard** [microsoftgraph/msgraph-sdk-java#734]
Using v3.3.0 on Android 23, 

in order to provide an instance of `IAuthenticationProvider` as described [here](https://github.com/microsoftgraph/msgraph-sdk-java#22-create-an-iauthenticationprovider-object) 

A dependancy on `java.util.concurrent.CompletableFuture`  (included in this library from the [core library](https://github.com/microsoftgraph/msgraph-sdk-java-core/blob/dev/src/main/java/com/microsoft/graph/authentication/IAuthenticationProvider.java)) is required which is not available on Android <24 , even with [desugaring](https://developer.android.com/studio/write/java8-support-table)  as prescribed [here](https://github.com/microsoftgraph/msgraph-sdk-java#7-supported-java-versions).

1. Am I missing some configuration or instruction to use this with Android, say 23? 
2. Is there a more detailed description of Android version support for this library as [this](https://github.com/microsoftgraph/msgraph-sdk-java#7-supported-java-versions) seems vague for Android <26? 
3. Is support for older versions of this library (for example v1.5 which seems to work down to Android 19) provided and can these older versions be reliably used going forward?

I appreciate any feedback 
[AB#9149](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9149)

**Comment by baywet** [comment]
Hi @dabarnard ,
Thanks for reaching out. I'll try to explain the context here, don't hesitate to ask follow-up questions if I'm not clear enough on some aspects.

The Java SDK (this library) is mainly meant to be used in Java projects (by this I mean on the full VMs) and on Java 8+.
It can be used by Android developers as well but with a few limitations. The main limitation requires a high API level by default (26) because a lot of the dependencies we're using (azure-identity and its dependencies) also requires API level 26.
The important thing to note here is if your minimum API level is 26 or above, we guarantee (through linting tools) it will work and we'll help you if you run into issues.

Now, if you want to target a lower API level, you have a few options:

- Enable desugaring, import backport libraries like [retrofuture](https://github.com/retrostreams/android-retrofuture) or [retrofix](https://github.com/SgtSilvio/android-retrofix) and hope things will work (depends on the minimum API level your app targets)
- Downgrade the SDK to 2.X as it on requires 19 and up in theory. The important caveat here is we didn't have any linting tool to guarantee the SDK wasn't using an API from a higher API level, so we don't know for sure it'll work. Also we're not updating that branch anymore, no bugfixes, no new APIs freshly available on Microsoft Graph...
- Not use the SDK and craft requests manually (painful, we know).

The important thing to note here is all those options are workarounds and we won't be providing support for any of those.
Don't hesitate to share your steps if you choose option one, we'll be happy to include additional details in the documentation.
That's the situation today. It is not great but it's better than yesterday since we now have an API level that's supported and we guarantee it will work through linting.

Without revealing too much, the azure identity team (our main dependency besides gson and okhttpclient) is thinking about releasing a new set of libraries specially for android which would require a much lower API level. If/when this releases it could mean multiple things for us that are undecided yet: do we create a separate android library? do we rework this one to lower the required API version and switch our azure identity dependency? ship multiple variants? (like guava does)...
You can follow their progress [here](https://github.com/Azure/azure-sdk-for-android/issues/120) don't hesitate to comment there to provide your feedback.

Hopefully this clarifies the situation.

**Comment by dabarnard** [comment]
Thanks for getting back to me and for being so detailed in your response.

I think your suggested option of creating the requests manually seems to be our only option at this stage. Especially since 2.x yields the same error described [here](https://github.com/microsoftgraph/msgraph-sdk-java/issues/530#issuecomment-706412101) and which you have stated  [will not be fixed](https://github.com/microsoftgraph/msgraph-sdk-java/issues/530#issuecomment-707712016).

It is promising to hear that some options might become available in the future though. I will hold thumbs and keep an eye on the progress you linked.

As a side note. Since Microsoft has announced the [shift from the EWS endpoint](https://techcommunity.microsoft.com/t5/exchange-team-blog/upcoming-changes-to-exchange-web-services-ews-api-for-office-365/ba-p/608055) which we have used up to now for Exchange Online users, a large void is now left for Android developers wishing to interface to Microsoft's endpoints targeting devices running Android 19 - 26. 

I know my use-case is fairly niche (we run a tablet app and Android tablets do lag behind phones in terms of Android version - even many Android 4.4 tablets are still fairly popular), but it is far from ideal being required to switch to the Graph API without support for users on older devices. 

Saying that, I know this is not your doing and I would like to say thanks for taking the time to answer me as you have and for the work you are doing on the library.

**Comment by baywet** [comment]
Thanks for the additional feedback, this is really precious!

Tagging @mairissi (program manager for the Java SDK) for visibility on the planning cycles.
