### ISSUE TITLE
Getting InternalServerError: Unable to find target address" in GET https://graph.microsoft.com/v1.0/organization?%24select=displayName

### ISSUE THREAD

**Issue by atulgpt** [microsoftgraph/msgraph-sdk-java#823]
### Expected behavior
I am calling organisation api as below
```kotlin
graphServiceClient.organization()
     .buildRequest()
     .select("displayName").get().currentPage
```
For normal users(in microsoft tenant), it should retrun empty list

### Actual behavior
While calling the above api, it is giving 500 Internal server error. Actual response is as below
```json
GET https://graph.microsoft.com/v1.0/organization?%24select=displayName
SdkVersion : graph-java/v2.10.0
Authorization : [PII_REDACTED]
500 : Internal Server Error
client-request-id : 6a83fc4a-4c4a-413a-916d-94c350f098e4
Content-Type : application/json
Date : Thu, 15 Jul 2021 05:22:21 GMT
request-id : bf4e22be-d4db-44d7-84fc-49652258aef5
Strict-Transport-Security : max-age=31536000
Transfer-Encoding : chunked
Vary : Accept-Encoding
x-ms-ags-diagnostic : {"ServerInfo":{"DataCenter":"South India","Slice":"E","Ring":"2","ScaleUnit":"002","RoleInstance":"MA1PEPF00001B2F"}}
{
  "error": {
    "code": "InternalServerError",
    "message": "Unable to find target address",
    "innerError": {
      "date": "2021-07-15T05:22:22",
      "request-id": "bf4e22be-d4db-44d7-84fc-49652258aef5",
      "client-request-id": "6a83fc4a-4c4a-413a-916d-94c350f098e4"
    }
  }
}
```
But for business users(other than Microsoft normal tenant), it is working fine

### Steps to reproduce the behavior
This is reproducible every time for personal microsoft account(with domail @hotmail.com) with the code
```kotlin
graphServiceClient.organization()
     .buildRequest()
     .select("displayName").get().currentPage
```

 
[AB#10223](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10223)

**Comment by baywet** [comment]
Hi @atulgpt 
Thanks for reaching out. (long time!)
The [documentation](https://docs.microsoft.com/en-us/graph/api/organization-get?view=graph-rest-1.0&tabs=http#permissions) already states this endpoint is not supported for personal accounts.
And this makes sense at personal accounts are not part of organizations (tenants).
I'm not sure what's the issue here?

Also, this repo is dedicated to issues about the SDK itself, since this is a "service issue", you should repost on Microsoft Q&A or using the "Feedback" section at the bottom of the documentation page so it gets to the right service team.
Closing.

**Comment by atulgpt** [comment]
@baywet Thanks for your response and clarification. Issue is that now we are recieving 500 server error intially it used to send empty list. 
Also thanks a lot for pointing out the right sources to file this issue.

**Comment by baywet** [comment]
Ah ok, it might be worth contacting the service team through the resources I shared in my previous answer if the service behaviour has changed.
