### ISSUE TITLE
New Attribute in Model (Identity.java) to track Email

### ISSUE THREAD

**Issue by Jatish-Khanna** [microsoftgraph/msgraph-sdk-java#851]
[Feature] Track new Identity Attribute Email
This new attribute (email) will track the email ID of the user.
It will be helpful in case of Developers doesn't have direct access to Azure OID (ID) attribute whereas Email is available to match and track user

    /**
     * The Display Name.
     * The identity's display name. Note that this may not always be available or up to date. 
     * For example, if a user changes their email, the API may show the new value in a future response, 
     * but the items associated with the user won't show up as having changed when using delta.
     */
    @SerializedName(value = "email", alternate = {"Email"})
    @Expose
	@Nullable
    public String email;

package com.microsoft.graph.models;
class: Identity.java

### Steps to reproduce the behavior

 
[AB#10766](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10766)

**Comment by baywet** [comment]
Hey @Jatish-Khanna 
Thanks for reaching out.

Which calls would that be helpful for? Can you provide a couple of examples please?

For your information, this SDK is automatically generated from the API metadata the service teams provide us. We never make changes to it directly but rely instead on the [generator](https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator), the part that's handcrafted is [the core library](https://github.com/microsoftgraph/msgraph-sdk-java-core).

So adding properties like that would have to be done at a service level.

Now sometimes the service teams don't necessarily describe some properties the service returns, which means properties don't get added to the models. This is especially the case for any property that's of type "IdentitySet", and we're working with the service teams to get this fixed. however in the mean-time, you can find any property that's returned by the service but doesn't exist in the type definition in the additional data manager.

**Comment by Jatish-Khanna** [comment]
@baywet thank you for your quick response. I understand the properties are autogenerated and have been included via the generator. 

One of the example where this would help in the usecase for business-

  Steps:
  1. Create the Permissions on the files/items in the Sharepoint/Drive via Graph API
  2. These will respond the GrantedTo includes the identity details as grantedTo.user.email and two other attributes including id and displayName
  3. Where removing the permission granted to the user based on a different account e.g. 
      User A as Owner of the Site/DocumentLibrary/Item request to remove User B permissions whereas I do track only UserEmails but Azure OID

  4. Find the permission ID returned at Step#2 for the user B with its email ID
  5. invoke Graph API to remove the permission via found permission ID

In another case, I need to store all the Azure OID mapping in the DB via email and find the permission ID for the respective OID to invoke Step$5

**Comment by baywet** [comment]
Thanks for the additional information here. So if I understand things correctly [the get permission endpoint](https://docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-1.0&tabs=http) currently doesn't return the email at all (not even in the additional data manager) and having this endpoint return that address would make the workflow you're describing much easier by removing the need to store OIDs on your side, correct?

**Comment by Jatish-Khanna** [comment]
@baywet  Yes, you are correct but I'm tried on three different tenants. Only in one tenant, it is returning the email attribute but the other two tenants. Although, your suggestion helped to fetch the information.

I couldn't find an example to iterate over the additionalManager but I've created my own example -

```
      JsonElement jsonElement = identity.additionalDataManager().getOrDefault(EMAIL_KEY, null);
      if(jsonElement != null) {
          log.info("{}", jsonElement.getAsString());
      }
```

Two points - 

1. Why do certain tenants respond with additionalDataManager whereas it is undefined in the Graph API?
2. If we can modify SDK to return Email and enable the Identity model to track **email** attribute instead of workaround on using additionDataManager?

**Comment by baywet** [comment]
Thanks for the additional information. The SDK is merely representing what the service is returning. We have two problems here:
1. The service is returning the email address inconsistently
2. The service doesn't describe it can return the email address (which is why we don't have a dedicated property in the SDK and have to go through the additional data manager)

In the case of the description, there's already an ongoing internal effort to replace references to the IdentitySet type by specialized types, it's already been done with the Microsoft Teams endpoints a couple of weeks ago which is why we bumped the version of the SDK from 3.X to 4.X.

In terms of the service behavior, my guess is that when they standardize the new properties, the behavior will become consistent.

I'm going to go ahead and close this issue as it is not an issue with the SDK itself but with the service. For the time being I suggest you still reference OIDs (in fact emails can technically change for a specific user but OIDs don't). If you want to get in touch with the service team to get attention on that matter, I suggest you [post on the Microsoft Graph files forum](https://docs.microsoft.com/en-us/answers/questions/topics/single/128339.html).
