### ISSUE TITLE
More unit testing

### ISSUE THREAD

**Issue by davidmoten** [microsoftgraph/msgraph-sdk-java#94]
As part of solving #90 (sending an email with attachments) I established what json was required to go to the Graph API and then set about ensuring that that json got there. This leads into a unit test (no interaction with an external service) so that as changes are made to the api we can confirm that important bits still work (like the json body of an http post being sent to the api).
The unit test below uses a special IHttpConnectionProvider that adds serialized bodies to a list (and does no network calls) which is then asserted after the action in question.
The api is blooming enormous so I don't imagine unit tests turning up overnight. However, as amendments are made to extension classes or even documentation added to the wiki, unit tests should ideally accompany the PR and this style is an option.
Once a strategy for coping with #90 is devised I can submit a unit test like this one:
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.concurrent.CopyOnWriteArrayList;

import org.json.JSONException;
import org.junit.Test;
import org.skyscreamer.jsonassert.JSONAssert;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;
import com.microsoft.graph.concurrency.ICallback;
import com.microsoft.graph.core.ClientException;
import com.microsoft.graph.http.IHttpProvider;
import com.microsoft.graph.http.IHttpRequest;
import com.microsoft.graph.http.IStatefulResponseHandler;
import com.microsoft.graph.logger.DefaultLogger;
import com.microsoft.graph.logger.LoggerLevel;
import com.microsoft.graph.models.extensions.Attachment;
import com.microsoft.graph.models.extensions.EmailAddress;
import com.microsoft.graph.models.extensions.FileAttachment;
import com.microsoft.graph.models.extensions.IGraphServiceClient;
import com.microsoft.graph.models.extensions.Message;
import com.microsoft.graph.models.extensions.Recipient;
import com.microsoft.graph.models.extensions.UserSendMailBody;
import com.microsoft.graph.requests.extensions.GraphServiceClient;
import com.microsoft.graph.serializer.DefaultSerializer;
import com.microsoft.graph.serializer.ISerializer;

public class SendEmailTest {

    @Test
    public void test() throws JSONException {
        DefaultLogger logger = new DefaultLogger();
        logger.setLoggingLevel(LoggerLevel.DEBUG);
        ISerializer serializer = new DefaultSerializer(logger);
        HttpProviderCapturing http = new HttpProviderCapturing(serializer);
        IGraphServiceClient client = GraphServiceClient //
                .builder() //
                .authenticationProvider(request -> {
                }) //
                .httpProvider(http) //
                .logger(logger) //
                .buildClient();

        String mailbox = "mailbox@blah.com";

        Recipient recipient = new Recipient();
        EmailAddress address = new EmailAddress();
        address.address = "someone@somewhere.com";
        recipient.emailAddress = address;

        // need to use a MyMessage to serialize attachments
        MyMessage message = new MyMessage();
        message.subject = "Test E-Mail";
        message.toRecipients = Collections.singletonList(recipient);

        FileAttachment att = new FileAttachment();
        att.contentBytes = "hello there!".getBytes(StandardCharsets.UTF_8);
        att.contentType = "text/plain";
        att.name = "hi.txt";
        att.oDataType = "#microsoft.graph.fileAttachment";
        message.addAttachment(att);

        client.users(mailbox) //
                .sendMail(message, true) //
                .buildRequest() //
                .post();
        // Do a non-strict comparison of the expected json with the captured json
        //TODO the expected JSON should be read from a resource file
        JSONAssert.assertEquals( //
                "{\"saveToSentItems\":true," //
                        + "\"message\":{" //
                        + "\"attachments\":[{\"contentBytes\":\"aGVsbG8gQU1TQSE=\",\"name\":\"hi.txt\",\"contentType\":\"text/plain\",\"@odata.type\":\"#microsoft.graph.fileAttachment\"}]" //
                        + ",\"subject\":\"Test E-Mail\",\"toRecipients\":[{\"emailAddress\":{\"address\":\"david.moten@amsa.gov.au\"}}]}}",
                http.bodies().get(0), false);
    }

    private static final class MyMessage extends Message {
        @SerializedName("attachments")
        @Expose
        private List<Attachment> attachmentsToSend = new ArrayList<>();

        public void addAttachment(FileAttachment att) {
            attachmentsToSend.add(att);
        }
    }

    // this class would become a top-level class for reuse
    private static final class HttpProviderCapturing implements IHttpProvider {

        private final ISerializer serializer;
        private final List<String> bodies = new CopyOnWriteArrayList<>();

        HttpProviderCapturing(ISerializer serializer) {
            this.serializer = serializer;
        }

        public List<String> bodies() {
            return bodies;
        }

        @Override
        public ISerializer getSerializer() {
            return serializer;
        }

        @Override
        public <Result, BodyType> void send(IHttpRequest request, ICallback<Result> callback, Class<Result> resultClass,
                BodyType serializable) {
            handle(serializable);
        }

        private <BodyType> void handle(BodyType serializable) {
            bodies.add(serializer.serializeObject(serializable));
        }

        @Override
        public <Result, BodyType> Result send(IHttpRequest request, Class<Result> resultClass, BodyType serializable)
                throws ClientException {
            handle(serializable);
            return null;
        }

        @Override
        public <Result, BodyType, DeserializeType> Result send(IHttpRequest request, Class<Result> resultClass,
                BodyType serializable, IStatefulResponseHandler<Result, DeserializeType> handler)
                throws ClientException {
            handle(serializable);
            return null;
        }
    }

}
[AB#6047](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6047)

**Comment by darrelmiller** [comment]
As you can imagine, maintaining a complete set of integration tests for the entire Graph V1.0 and beta surface area would be a very resource intensive effort, especially due to the rapid growth.  But we have a plan!   We currently generate code snippets in our reference documentation for many of our examples.  e.g. https://docs.microsoft.com/en-us/graph/api/driveitem-list-children?view=graph-rest-1.0&tabs=java

We are in the process of building a tools that will take those snippets and test those snippets against a test tenant with known data.  That project is what we call (Raptor)[https://github.com/microsoftgraph/msgraph-sdk-raptor].  Currently we only are doing testing on the C# snippets, but our roadmap is to perform these tests in all the supported languages.

This approach is scalable because it is the teams that create the APIs that create the tests and the developer experience team only own the infrastructure to do the automated tests.   I realize this does not address the problem in the short term, but I just wanted to assure you that we do have a plan and people working to ensure we get complete testing coverage in the future.

Additionally, we will be using this testing process as part of our onboarding efforts so this should enable us to prevent problems reaching the metadata in the first place.

**Comment by davidmoten** [comment]
My point with this issue was about unit testing not integration testing so a bit early to close. Why no unit testing of service interactions?

**Comment by davidmoten** [comment]
@baywet please reopen this issue because the answers given refer to integration tests against an endpoint with controlled data. That is not unit testing!

**Comment by baywet** [comment]
@davidmoten I'm going to describe the ideal situation we're working towards here:

- The service SDK (this repo) should only contain generated, very simple code, which building unit testing for doesn't provide a lot of value because it's a projection of the service metadata in Java. The service metadata is already tested and validated a numerous steps of the overall pipeline, the code-gen process is also tested at multiple steps, which includes the integration testing Darrel was referring to.
- The [core library](https://github.com/microsoftgraph/msgraph-sdk-java-core) should contain all the handcrafted coded that's required to go from the generated Java API to HTTP requests and back. This needs to be unit tested of course.

Today we're in a mixed stated and part of [the v3 work](https://github.com/microsoftgraph/msgraph-sdk-java/milestone/4) is to [move the code that's not generated into the core library](https://github.com/microsoftgraph/msgraph-sdk-java/issues/578). Once everything is at the right place, we should be able to write unit tests, report code coverage,... and get value from doing all of that.

Lastly "More unit testing" is a vague goal that's hard to measure (how do we know when we're done?). I'd much rather have some more tactical goals like "setup code coverage reporting for the repository", "implement unit tests for class X to test for Y/to reach 80% coverage" etc.

Hopefully this lengthy explanation helps shining lights on the general direction we're taking. And as always we do appreciate questions/comments or even contributions if you feel up to it!
