### ISSUE TITLE
SSL Error downloading document contents from Sharepoint using Graph API from Azure Spring Cloud application

### ISSUE THREAD

**Issue by ChrisBrat** [microsoftgraph/msgraph-sdk-java#949]
My spring boot application deployed in Azure Spring Cloud is executing requests against the Graph API using the Java microsoft-graph SDK - initially 3.2.0 and then the latest version.

 
All requests for sites, drives, driveitems are successful both locally on Windows 10 workstation and in Azure Spring Cloud container (JDK version 8 and 11)

but requests for driveitem contents specifically fail when executed in a deployed container due to "Caused by: java.io.EOFException: SSL peer shut down incorrectly".

The same code is able to retrieve the driveitem contents successfully from my local Windows 10 workstation.

Our app is using TLS 1.2

The graphServiceClient object is a singleton.

Below are two attempts to retrieve document contents using the SDK - with the asynch the error occurs when getting the InputStream

// Async
CompletableFuture<InputStream> inputStreamFuture = graphServiceClient.
                sites(siteId).
                drives(driveId).
                items(itemId).
                content().
                buildRequest().
                getAsync();

inputStream = inputStreamFuture.get(TIMEOUT, TimeUnit.SECONDS);

 

 

// Sync
DriveItem driveItem = graphServiceClient.
                sites(siteId).
                drives(driveId).
                items(itemId).
                buildRequest().
                get();

 

 

Any assistance or guidance with this issue is appreciated.

EDIT - > The content() step missing in the // Sync snip is a typo

**Comment by baywet** [comment]
Hi @ChrisBrat,
Thanks for reaching out.
My understanding of your issue is that only request to "content" fail, and only on the Azure Spring Cloud environment, other requests using the SDK function properly in every environment.

Side note, I believe the sync sample you provided should be

```Java
InputStream inputStream = graphServiceClient.
sites(siteId).
drives(driveId).
items(itemId).
content().
buildRequest().
get();
```

All that being said, a request to the content endpoint, leads to a [302 response](https://docs.microsoft.com/en-us/graph/api/driveitem-get-content?view=graph-rest-1.0&tabs=http#response) which redirects the client to the service which hosts the file (usually SharePoint if we're talking about OneDrive for business).

While [graph.microsoft.com support TLS 1.0 to 1.2 and a wide variety of cipher suites](https://www.ssllabs.com/ssltest/analyze.html?d=graph.microsoft.com&s=20.190.132.44), [SharePoint is restricted to TLS1.2 and fewer suites](https://www.ssllabs.com/ssltest/analyze.html?d=biret365.sharepoint.com&s=13.107.136.9&latest), [OneDrive consumer has a wider support but I believe this will change in the near future](https://www.ssllabs.com/ssltest/analyze.html?d=b0mpua-by3301.files.1drv.com).
A bit of context here: for security reasons, TLS 1.0 and 1.1 are being retired as well as some cipher suites, if SharePoint seems to be leading the charge here, most services will follow this more in the future.

While the SDK relies on OkHttp under the covers, [which offers a support for a wide variety of TLS versions and cipher suites](https://square.github.io/okhttp/tls_configuration_history/), the client can only "work" with the protocols and ciphers that are implemented by the JVM it's running on.

My guess of what's happening here, requests to graph.microsoft.com succeed as the protocol and cipher support is wider, when the application tries to get the content, it gets redirected to SharePoint, which has a narrower protocol and cipher support. Unfortunately this new set does not intersect with what the current JVM supports.

While I don't have first hand experience, here is what I recommend you to try:
- run `mvn dependency:list` or `gradle dependencies` and double check that all dependencies are up to date (mostly the SDK, the core SDK, and OkHttp)
- Tweak the Azure Spring Cloud service settings to try to get to a "newer JVM" (upgrading from 8 to 11 and from 11 to 17) or a "different" JVM (if possible)
- Tweak the Azure Spring Cloud service settings to see if some protocols are disabled by configuration for some reason
- Engage with the Azure Spring Cloud support so they help you through that effort
- Check the Zulu JVM supports the cipher suites and protocols listed out by the ssl lab test for SharePoint. (I believe Azure Spring Cloud is using Zulu but I couldn't find a source in the docs for that information)

Hopefully this lengthy post helps you troubleshoot the issue, let us know if you have further questions/comments and please post the resolution here as I'm sure it'll help others in similar situations in the future.

**Comment by ChrisBrat** [comment]
Hi @baywet  - yes, your understanding is correct.

Thank you very much - that gives me a direction to follow.

I'll try your recommendations and post feedback here.

**Comment by ChrisBrat** [comment]
Hello @baywet, 

Thank you for your assistance.

We eliminated the following as causes : 
* Versions 
* JDK 
* Cipher suites

A colleague finally resolved the issue - he identified that the Sharepoint host was blocked in the spoke vnet in the Azure Spring Cloud reference architecture.

Many thanks.

**Comment by baywet** [comment]
Thanks for sharing the information with everybody else here!
