### ISSUE TITLE
How to create a GraphServiceClient using a raw access token?

### ISSUE THREAD

**Issue by dagnelies** [microsoftgraph/msgraph-sdk-java#961]
Hi,

sorry for the dumb question, but how to create a GraphServiceClient  using a raw access token directly? I saw all kind of "authentication providers", but no way to provide the token directly.

If you are curious about the background of this use case, it's simply that our software is divided into different modules. One module is in charge of login, aquiring tokens and basic stuff, while other modules use these access tokens to call the graph API to provide some functionality.

**Comment by zengin** [comment]
We have a DelegateAuthenticationProvider which provides the described functionality:
https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/overview.md#delegateauthenticationprovider

Alternatively the TokenCredentialAuthProvider object can be pre-created to take advantage of default token cache implementations at the OS level when they are available, The example below uses an unsafe in-memory cache, but there are safe implementations in non-Linux OSes:
https://github.com/microsoftgraph/msgraph-sdk-raptor/blob/85358299f9d733118c32b726365ed33d727ff779/msgraph-sdk-raptor-compiler-lib/PermissionManager.cs#L272

Please let us know if this works for you.

**Comment by baywet** [comment]
To provide additional information and translate it to java terms, you can simply implement the [IAuthenticationProvider](https://github.com/microsoftgraph/msgraph-sdk-java-core/blob/dev/src/main/java/com/microsoft/graph/authentication/IAuthenticationProvider.java) interface to retrieve the token from your token store/communication layer and pass the implementation to the GraphServiceClient.

**Comment by dagnelies** [comment]
Indeed, that's what I did anyway since there is no such class as `DelegateAuthenticationProvider` in this Java MS Graph SDK as far as I can tell:

https://github.com/microsoftgraph/msgraph-sdk-java/search?q=DelegateAuthenticationProvider

It's quite ironic that you can provide the Graph SDK all kind of advanced authentication callback mechanisms, but that simply providing the resulting access token itself is complicated.

Here is what I used in the end:

```java
IAuthenticationProvider authProvider = new IAuthenticationProvider() {
	@Override
	public CompletableFuture<String> getAuthorizationTokenAsync(@NotNull URL requestUrl) {
		CompletableFuture<String> alreadyThere = new CompletableFuture<>();
		String authToken = "the-jwt-token-that-was-obtained-somehow";
		alreadyThere.complete(authToken);
		return alreadyThere;
	}
};

GraphServiceClient<Request> graphClient = GraphServiceClient
		.builder()
		.authenticationProvider(authProvider)
		.buildClient();
```

...it just feels very clunky.

**Comment by baywet** [comment]
Some context:

## Current implementation

Leverage [BaseAuthenticationProvider](https://github.com/microsoftgraph/msgraph-sdk-java-core/blob/dev/src/main/java/com/microsoft/graph/authentication/BaseAuthenticationProvider.java) and call `shouldAuthenticateRequestWithUrl` to know whether or not you should return a token for the request.

Also, the annotation should be Nonnull, not NotNull.

## Lack of delegate provider - reasons behind it

This is partly due to historical reasons: lots of improvements/refactoring to the authentication story with v3 that removed a lot of custom code to rely on Azure Identity. This is also partly due to the fact that we were kind of expecting Azure Identity to add support for it.
And lastly, we try to discourage people from doing that as often they don't have a strong requirement to pass a token, they just want the authentication to work. Providing the token straight brings other issues, what to do when the token expires/is invalidated? Does the delegate check for valid URLs before returning a token? How is the token stored?... And "pushing" people to use Azure identity solves a lot of those issues, especially around secure token storage/caching, renewal and so on.

## Looking aahead

We're working on a revamp of our generation story and [kiota, the next generator](https://github.com/microsoft/kiota), already includes infrastructure to [support those kind of scenarios](https://github.com/microsoft/kiota/blob/main/abstractions/java/lib/src/main/java/com/microsoft/kiota/authentication/BaseBearerTokenAuthenticationProvider.java)

## Until then?

Now, we understand this newer version is a couple of months out at least, and in the meantime people need solutions for now.
If you're willing to submit a pull request [on the core repository](https://github.com/microsoftgraph/msgraph-sdk-java-core/), we'll be happy to review and merge it so everyone benefits a delegated handler.

**Comment by dagnelies** [comment]
Well, if it is gonna change anyway, I guess it makes more sense to simply wait for it. ;)
Thanks for the responsiveness overall.

**Comment by zengin** [comment]
Sorry for the confusion, I reviewed a few dotnet issues that day before this and coming from notifications, I thought that this was raised in the dotnet repo, my bad.
