### ISSUE TITLE
Loading all contacts using the Microsoft Graph API sometimes looses/skips pages

### ISSUE THREAD

**Issue by mptardy** [microsoftgraph/msgraph-sdk-java#968]
### Expected behavior
Loading all contacts of an account we expect that **all** contacts are being loaded.

### Actual behavior
Sometimes, some pages are being skipped, meaning $count does not match the number of contacts loaded iterating over all pages.

### Steps to reproduce the behavior
I've posted my question on [stackoverflow](https://stackoverflow.com/questions/70374893/loading-all-contacts-using-the-microsoft-graph-api-sometimes-looses-pages), where you can see the code we use to load all contacts using paging.

We run this code every 5 mins and sometimes, the $count and the number of contacts loaded does not match up. Verifying the numbers manually we can say, that $count was always correct and some pages were skipped while loading the contacts. 

Currently, we use microsoft-graph 5.8.0 and azure-identiy 1.4.2.

**Comment by ramsessanchez** [comment]
Hi @mptardy, I believe this issue is similar to an issue we've had before in the core repo, since we currently don't have an iterator in the Java core library.
https://github.com/microsoftgraph/msgraph-sdk-java-core/issues/350
Let me know whether this helps or not. Thanks!

**Comment by mptardy** [comment]
Hi @ramsessanchez 
I had a look at microsoftgraph/msgraph-sdk-java-core#350 and I don't think it is related to this issue. In microsoftgraph/msgraph-sdk-java-core#350 they talk about how to iterate over pages and that some **fields** are missing in the returned object.

These are not issues I have. My issue is, that from time to time a page is being skipped and I end up with less contacts loaded than there are.

Thanks, you help is much appreciated.

**Comment by ramsessanchez** [comment]
Hi @mptardy, Apologies for the extended delay, have been out on holiday. I hope that your new years is going well! 
I suspect that the faulty issue may be related to the way that the while loop that handles the data loading is set up. This is partially why I recommended that you look into the issue in [msgraph-sdk-java-core#350](https://github.com/microsoftgraph/msgraph-sdk-java-core/issues/350) as it contains a very useful while loop that may help you handle/load the data, my apologies once again as I should have been more clear on this. 
Also, in your stack overflow post you mention that this behavior is only caused sometimes? While I would suggest attempting to adjust the while loop, as mentioned above, I would also like to request some more information relating to the behavior that you suspect is causing this to happen. Any suspicions or leads would be helpful in attempting to resolve this issue, especially since it might be difficult to replicate considering the large quantity of users that you are managing. Any and all additional information would be helpful, thanks!

**Comment by mptardy** [comment]
Hi @ramsessanchez 

Thanks again for your help. I had another look at microsoftgraph/msgraph-sdk-java-core#350 and I cannot find a difference in how we use the paging api. We don't use a do-while-loop, but the calls we are doing are exactly the same.

We've increased the page size vom 100 to 1000 for loading a bit more than 3000 contacts and we have not seen the issues since. It look to me like a caching problem on the server side.
